"""Add moderation models

Revision ID: 402d486af66a
Revises: a9958535142f
Create Date: 2026-09-26 11:06:11.939334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '402d486af66a'
down_revision: Union[str, None] = 'a9958535142f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('reporter_user_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('details', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_reports_id'), 'content_reports', ['id'], unique=False)
    op.create_index(op.f('ix_content_reports_project_id'), 'content_reports', ['project_id'], unique=False)
    op.create_index(op.f('ix_content_reports_reporter_user_id'), 'content_reports', ['reporter_user_id'], unique=False)
    op.add_column('dubbing_projects', sa.Column('moderation_status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dubbing_projects', 'moderation_status')
    op.drop_index(op.f('ix_content_reports_reporter_user_id'), table_name='content_reports')
    op.drop_index(op.f('ix_content_reports_project_id'), table_name='content_reports')
    op.drop_index(op.f('ix_content_reports_id'), table_name='content_reports')
    op.drop_table('content_reports')
    # ### end Alembic commands ###
