"""Add likes and views

Revision ID: 96f47744ccb9
Revises: 402d486af66a
Create Date: 2026-09-26 11:23:18.974177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f47744ccb9'
down_revision: Union[str, None] = '402d486af66a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dubbing_likes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_user_like')
    )
    op.create_index(op.f('ix_dubbing_likes_id'), 'dubbing_likes', ['id'], unique=False)
    op.create_index(op.f('ix_dubbing_likes_project_id'), 'dubbing_likes', ['project_id'], unique=False)
    op.create_index(op.f('ix_dubbing_likes_user_id'), 'dubbing_likes', ['user_id'], unique=False)
    op.add_column('dubbing_projects', sa.Column('view_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dubbing_projects', 'view_count')
    op.drop_index(op.f('ix_dubbing_likes_user_id'), table_name='dubbing_likes')
    op.drop_index(op.f('ix_dubbing_likes_project_id'), table_name='dubbing_likes')
    op.drop_index(op.f('ix_dubbing_likes_id'), table_name='dubbing_likes')
    op.drop_table('dubbing_likes')
    # ### end Alembic commands ###
