"""Add DubbingProject and DubbingExport

Revision ID: a9958535142f
Revises: 82db0755cbda
Create Date: 2026-09-26 10:30:28.070443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9958535142f'
down_revision: Union[str, None] = '82db0755cbda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dubbing_exports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('output_video_id', sa.String(length=100), nullable=False),
    sa.Column('download_url', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.String(length=50), nullable=True),
    sa.Column('file_size_bytes', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dubbing_exports_id'), 'dubbing_exports', ['id'], unique=False)
    op.create_index(op.f('ix_dubbing_exports_project_id'), 'dubbing_exports', ['project_id'], unique=False)
    op.create_table('dubbing_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('duration_seconds', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dubbing_projects_id'), 'dubbing_projects', ['id'], unique=False)
    op.create_index(op.f('ix_dubbing_projects_user_id'), 'dubbing_projects', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dubbing_projects_user_id'), table_name='dubbing_projects')
    op.drop_index(op.f('ix_dubbing_projects_id'), table_name='dubbing_projects')
    op.drop_table('dubbing_projects')
    op.drop_index(op.f('ix_dubbing_exports_project_id'), table_name='dubbing_exports')
    op.drop_index(op.f('ix_dubbing_exports_id'), table_name='dubbing_exports')
    op.drop_table('dubbing_exports')
    # ### end Alembic commands ###
