"""Add comments

Revision ID: bc2a9e7650d6
Revises: 96f47744ccb9
Create Date: 2026-09-26 11:31:17.555048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc2a9e7650d6'
down_revision: Union[str, None] = '96f47744ccb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dubbing_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('hidden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hidden_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dubbing_comments_id'), 'dubbing_comments', ['id'], unique=False)
    op.create_index(op.f('ix_dubbing_comments_project_id'), 'dubbing_comments', ['project_id'], unique=False)
    op.create_index(op.f('ix_dubbing_comments_user_id'), 'dubbing_comments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dubbing_comments_user_id'), table_name='dubbing_comments')
    op.drop_index(op.f('ix_dubbing_comments_project_id'), table_name='dubbing_comments')
    op.drop_index(op.f('ix_dubbing_comments_id'), table_name='dubbing_comments')
    op.drop_table('dubbing_comments')
    # ### end Alembic commands ###
