"""add retention_expires_at to dubbing_exports

Revision ID: e08228b2020a
Revises: d4e5f6a7b8c9
Create Date: 2026-09-28 13:06:55.045081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e08228b2020a'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dubbing_exports', sa.Column('retention_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dubbing_exports', 'retention_expires_at')
    # ### end Alembic commands ###
