/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useEffect, useState, ReactNode } from 'react';

export type Language = 'TR' | 'EN';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<string, Record<Language, string>> = {
  // Navbar
  'nav.play': { TR: 'Oyna', EN: 'Play' },
  'nav.scenes': { TR: 'Sahneler', EN: 'Scenes' },
  'nav.dubs': { TR: 'Dublajlar', EN: 'Dubs' },
  'nav.daily': { TR: 'Günün Dublajı', EN: 'Daily Dub' },
  'nav.language': { TR: 'Dil', EN: 'Language' },
  'nav.login': { TR: 'Giriş Yap', EN: 'Login' },
  'nav.register': { TR: 'Kayıt Ol', EN: 'Sign Up' },
  'nav.moderation': { TR: 'Moderasyon', EN: 'Moderation' },
  'nav.system': { TR: 'Sistem (Ops)', EN: 'System (Ops)' },
  'nav.account_registered': { TR: 'Kayıtlı Hesap', EN: 'Registered Account' },
  'nav.level': { TR: 'Seviye 1', EN: 'Level 1' },
  'nav.account_section': { TR: 'Hesabın', EN: 'Your account' },
  'nav.vip_active': { TR: 'VIP Aktif', EN: 'VIP Active' },
  'nav.vip_join': { TR: 'VIP ol', EN: 'Go VIP' },
  'nav.vip_active_desc': { TR: '1080p ve AI ses özelliklerin açık.', EN: '1080p and AI voice features are enabled.' },
  'nav.vip_join_desc': { TR: '1080p çıktı ve AI ses modunu aç.', EN: 'Unlock 1080p export and AI voice mode.' },
  'nav.moderation_panel': { TR: 'Moderasyon Paneli', EN: 'Moderation Panel' },
  'nav.system_status': { TR: 'Sistem Durumu (Ops)', EN: 'System Status (Ops)' },
  'drop.profile': { TR: 'Profilim', EN: 'My Profile' },
  'drop.membership': { TR: 'Üyeliğim', EN: 'Membership' },
  'drop.library': { TR: 'Kataloğum', EN: 'My Library' },
  'drop.scenes': { TR: 'Sahnelerim', EN: 'My Scenes' },
  'drop.favorites': { TR: 'Favorilerim', EN: 'Favorites' },
  'drop.credits': { TR: 'Kredilerim', EN: 'My Credits' },
  'drop.account': { TR: 'Hesabım', EN: 'Settings' },
  'drop.logout': { TR: 'Çıkış Yap', EN: 'Logout' },
  
  // Account Settings
  'account.title': { TR: 'Hesap Ayarları', EN: 'Account Settings' },
  'account.save': { TR: 'Tümünü kaydet', EN: 'Save all' },
  'account.discord_link': { TR: 'Discord Hesabını Bağla', EN: 'Link Discord Account' },
  'account.discord_linked': { TR: 'Discord Bağlandı', EN: 'Discord Linked' },
  'account.delete': { TR: 'Hesabımı silmek istiyorum', EN: 'I want to delete my account' },

  // Membership & Credits
  'vip.button': { TR: 'Şimdi VIP Ol', EN: 'Become VIP Now' },
  'credits.buy': { TR: 'Kredi Al', EN: 'Buy Credits' },

  // Auth Page
  'auth.hero.title1': { TR: 'Kendi sesinle', EN: 'Take the stage' },
  'auth.hero.title2': { TR: 'sahnede yerini al.', EN: 'with your own voice.' },
  'auth.hero.desc': { TR: 'Favori filmlerine, popüler dizilere ve viral videolara kendi sesinle dublaj yap. Arkadaşlarınla paylaş veya toplulukta öne çık.', EN: 'Dub your favorite movies, popular series, and viral videos with your own voice. Share with friends or stand out in the community.' },
  'auth.login.title': { TR: 'Tekrar Hoş Geldin', EN: 'Welcome Back' },
  'auth.login.desc': { TR: 'Kaldığın yerden devam etmek için giriş yap.', EN: 'Log in to continue where you left off.' },
  'auth.register.title': { TR: 'Maceraya Katıl', EN: 'Join the Adventure' },
  'auth.register.desc': { TR: 'Ücretsiz hesabını oluştur ve ilk dublajını yap.', EN: 'Create your free account and make your first dub.' },
  'auth.feature.scenes': { TR: '+5.000 Sahne', EN: '+5,000 Scenes' },
  'auth.feature.ai_mix': { TR: 'AI Destekli Mix', EN: 'AI-assisted Mix' },
  'auth.quote.1': { TR: '"Senin sorunun ne biliyor musun?"', EN: '"Do you know what your problem is?"' },
  'auth.quote.2': { TR: '"Hadi oradan!"', EN: '"Oh, come on!"' },
  'auth.quote.3': { TR: '"Ben de tam onu diyecektim."', EN: '"I was just about to say that."' },
  'auth.quote.4': { TR: '"Sessizlik!"', EN: '"Silence!"' },
  'auth.username': { TR: 'Kullanıcı Adı', EN: 'Username' },
  'auth.email': { TR: 'E-posta Adresi', EN: 'Email Address' },
  'auth.password': { TR: 'Şifre', EN: 'Password' },
  'auth.waiting': { TR: 'Bekleniyor...', EN: 'Please wait...' },
  'auth.login.action': { TR: 'Giriş Yap', EN: 'Log In' },
  'auth.register.action': { TR: 'Hesap Oluştur', EN: 'Create Account' },
  'auth.or': { TR: 'veya', EN: 'or' },
  'auth.no_account': { TR: 'Hesabın yok mu?', EN: "Don't have an account?" },
  'auth.have_account': { TR: 'Zaten hesabın var mı?', EN: 'Already have an account?' },
  'auth.signup_link': { TR: 'Kayıt ol', EN: 'Sign up' },
  'auth.login_link': { TR: 'Giriş yap', EN: 'Log in' },
  'auth.register_success': { TR: 'Kayıt başarılı! Lütfen giriş yapın.', EN: 'Registration successful! Please log in.' },
  'auth.login_success': { TR: 'Giriş başarılı! Stüdyoya yönlendiriliyorsunuz.', EN: 'Login successful! Taking you to the studio.' },
  'auth.generic_error': { TR: 'Bir hata oluştu.', EN: 'Something went wrong.' },

  // Studio
  'studio.badge': { TR: 'Tarayıcı tabanlı dublaj stüdyosu', EN: 'Browser-based dubbing studio' },
  'studio.hero.line1': { TR: 'Kendi sesinle komik', EN: 'Create funny dubbed' },
  'studio.hero.accent': { TR: 'dublaj videoları', EN: 'videos with your voice' },
  'studio.hero.line2': { TR: 'oluştur', EN: '' },
  'studio.hero.description': { TR: 'Hazır sahne seç ya da kendi videonu yükle, repliği oku, altyazılı MP4 olarak indir.', EN: 'Choose a ready-made scene or upload your own video, read the lines, and download a subtitled MP4.' },
  'studio.cta.start': { TR: 'Hemen Dublaj Yap', EN: 'Start Dubbing' },
  'studio.cta.templates': { TR: 'Hazır Sahneleri Keşfet', EN: 'Explore Ready Scenes' },
  'studio.trust.own_video': { TR: 'Kendi videonu kullan', EN: 'Use your own video' },
  'studio.trust.no_copyright': { TR: 'Telifli içerik yükleme', EN: 'Do not upload copyrighted content' },
  'studio.trust.no_impersonation': { TR: 'Kimseyi taklit etme', EN: 'Do not impersonate anyone' },
  'studio.step.source': { TR: 'Sahneyi seç', EN: 'Choose a scene' },
  'studio.step.record': { TR: 'Replikleri kaydet', EN: 'Record the lines' },
  'studio.step.download': { TR: 'MP4’ü indir', EN: 'Download MP4' },
  'studio.preview.title': { TR: 'Çıktı örneği', EN: 'Output preview' },
  'studio.preview.subtitle': { TR: 'Repliğini oku → MP4 indir', EN: 'Read your line → download MP4' },
  'studio.preview.line1': { TR: 'Toplantı beş dakika sürecek dediler…', EN: 'They said the meeting would take five minutes…' },
  'studio.preview.line2': { TR: 'Tüm gün süren o toplantı…', EN: 'That meeting lasted all day…' },
  'studio.preview.line3': { TR: 'Neyse, kahve molası…', EN: 'Anyway, coffee break…' },
  'studio.feature.voice': { TR: 'Kendi sesim', EN: 'My own voice' },
  'studio.feature.timeline': { TR: 'Timeline replik', EN: 'Timeline-based lines' },
  'studio.feature.export': { TR: 'MP4 export', EN: 'MP4 export' },
  'studio.feature.subtitles': { TR: 'Altyazı gömme', EN: 'Burned-in subtitles' },
  'studio.feature.copyright': { TR: 'Telif bilinci', EN: 'Copyright awareness' },
  'studio.demo.title': { TR: 'Public demo sınırları etkin', EN: 'Public demo limits are active' },
  'studio.demo.limits': { TR: 'En fazla {size} MB / {duration} saniye video, replik başına {recording} MB kayıt ve IP başına günde {exports} export kullanılabilir.', EN: 'You can use videos up to {size} MB / {duration} seconds, recordings up to {recording} MB per line, and {exports} exports per IP each day.' },
  'studio.demo.retention': { TR: 'Bu public demo dosyalarınızı kalıcı olarak saklamaz. Medya temizleme politikası {hours} saatliktir.', EN: 'This public demo does not store your files permanently. Media is cleaned up after {hours} hours.' },
  'studio.source.eyebrow': { TR: '01 / Kaynak video', EN: '01 / Source video' },
  'studio.source.title': { TR: 'Sahneni seç', EN: 'Choose your scene' },
  'studio.source.change': { TR: 'Kaynağı değiştir', EN: 'Change source' },
  'studio.source.upload': { TR: 'Kendi videonu yükle', EN: 'Upload your video' },
  'studio.source.template': { TR: 'Hazır sahne seç', EN: 'Choose a ready scene' },
  'studio.video.validating': { TR: 'Video doğrulanıyor', EN: 'Validating video' },
  'studio.video.checking': { TR: 'Süre ve format kontrol ediliyor…', EN: 'Checking duration and format…' },
  'studio.video.ready': { TR: 'Video kullanıma hazır', EN: 'Video is ready' },
  'studio.editor.eyebrow': { TR: '02 / Dublaj stüdyosu', EN: '02 / Dubbing studio' },
  'studio.editor.title': { TR: 'Sahneyi seslendir', EN: 'Dub the scene' },
  'studio.plan.free': { TR: 'Ücretsiz · 720p export', EN: 'Free · 720p export' },
  'studio.plan.vip': { TR: 'VIP · 1080p export', EN: 'VIP · 1080p export' },
  'studio.mode.voice': { TR: 'Kendi sesim', EN: 'My voice' },
  'studio.mode.ai': { TR: 'AI ses · VIP', EN: 'AI voice · VIP' },
  'studio.empty.title': { TR: 'Önce bir kaynak seç', EN: 'Choose a source first' },
  'studio.empty.description': { TR: 'Hazır sahne seçtiğinde veya videonu yüklediğinde replik zaman çizelgesi burada oluşacak.', EN: 'Your line timeline will appear here after you choose a ready scene or upload a video.' },
  'studio.empty.upload': { TR: 'Video yükle', EN: 'Upload video' },
  'studio.catalog.title': { TR: 'Sahne Kataloğu', EN: 'Scene Catalog' },
  'studio.catalog.description': { TR: 'Dublaj yapmak için popüler bir sahne seç veya doğrudan projeye başla.', EN: 'Choose a popular scene to dub or start a project directly.' },
  'studio.auth_required': { TR: 'Lütfen giriş yapın.', EN: 'Please log in.' },
  'studio.unauthorized': { TR: 'Bu sayfaya erişim yetkiniz yok.', EN: 'You do not have permission to access this page.' },
  'studio.export.ready': { TR: '03 / Export hazır', EN: '03 / Export ready' },
  'studio.export.title': { TR: 'Dublajın paylaşılmaya hazır.', EN: 'Your dub is ready to share.' },
  'studio.export.download': { TR: 'MP4 indir', EN: 'Download MP4' },
  'studio.export.next': { TR: 'Sırada ne var?', EN: "What's next?" },
  'studio.export.description': { TR: 'Sonucu indirebilir, sosyal medyada paylaşabilir veya yeni projeye başlayabilirsin.', EN: 'Download the result, share it on social media, or start a new project.' },
  'studio.export.copy': { TR: 'Linki Kopyala', EN: 'Copy Link' },
  'studio.export.share_x': { TR: "X'te Paylaş", EN: 'Share on X' },
  'studio.export.same_video': { TR: 'Aynı video ile dene', EN: 'Try the same video' },
  'studio.export.new_video': { TR: 'Yeni video', EN: 'New video' },
  'studio.template.media_soon': { TR: 'Demo medya yakında', EN: 'Demo media coming soon' },
  'studio.template.media_hint': { TR: 'Replikleri düzenle ve mikrofon kayıt akışını dene. Kendi videonu bağlayarak tam export alabilirsin.', EN: 'Edit the lines and try the microphone recording flow. Add your own video for a complete export.' },
  'studio.template.license': { TR: 'Lisans', EN: 'License' },
  'studio.template.source': { TR: 'Kaynak', EN: 'Source' },
  'studio.template.seconds': { TR: 'sn', EN: 'sec' },
  'studio.template.lines': { TR: 'replik', EN: 'lines' },
  'studio.ai.vip_only': { TR: 'AI ses modu VIP üyelere özeldir.', EN: 'AI voice mode is available to VIP members only.' },
  'studio.ai.login_vip': { TR: 'AI ses modu için giriş yapıp VIP üyeliği etkinleştirin.', EN: 'Log in and activate VIP membership to use AI voice mode.' },
  'studio.lipsync.title': { TR: 'Dudak Senkronizasyonu (Deneysel)', EN: 'Lip Sync (Experimental)' },
  'studio.lipsync.description': { TR: 'Yüz hareketlerini dublaj sesine göre işler', EN: 'Matches facial movement to the dubbed audio' },
  'studio.lipsync.vip_required': { TR: 'VIP üyelik gerektirir', EN: 'VIP membership required' },
  'studio.lipsync.vip_only': { TR: 'Yalnızca aktif VIP üyeler kullanabilir.', EN: 'Available only to active VIP members.' },
  'studio.ai.vip_title': { TR: 'AI ses modu VIP özelliğidir', EN: 'AI voice mode is a VIP feature' },
  'studio.ai.vip_description': { TR: 'Kendi sesinle dublaj ücretsizdir. AI ses ve 1080p export için VIP üyeliğini etkinleştir.', EN: 'Dubbing with your own voice is free. Activate VIP for AI voice and 1080p export.' },
  'studio.ai.vip_cta': { TR: 'VIP özelliklerini gör', EN: 'View VIP features' },
  'studio.ai.notice': { TR: 'Opsiyonel mod: Yazdığın metin, gerçek kişileri taklit etmeyen hazır bir Türkçe yapay sesle okunur.', EN: 'Optional mode: Your text is read with a preset synthetic voice that does not imitate a real person.' },
  'studio.ai.script': { TR: 'Dublaj metni', EN: 'Dubbing script' },
  'studio.ai.placeholder': { TR: 'Örn: Toplantı beş dakika sürecek dediklerinde ben…', EN: 'Example: When they said the meeting would take five minutes…' },
  'studio.ai.mute': { TR: 'Orijinal sesi kıs', EN: 'Lower original audio' },
  'studio.ai.mute_desc': { TR: 'AI dublajı öne çıkarır', EN: 'Makes the AI dub easier to hear' },
  'studio.ai.subtitles': { TR: 'Altyazıyı göm', EN: 'Burn in subtitles' },
  'studio.ai.subtitles_desc': { TR: 'Metni videoda gösterir', EN: 'Shows the text in the video' },
  'studio.ai.create': { TR: 'AI Sesle Video Oluştur', EN: 'Create Video with AI Voice' },
  'studio.ai.write_first': { TR: 'Devam etmek için dublaj metnini yazın.', EN: 'Enter the dubbing script to continue.' },
  'studio.job.status': { TR: 'Gerçek job durumu', EN: 'Live job status' },
  'studio.job.queued': { TR: 'Export sırasına alınıyor…', EN: 'Export is being queued…' },
  'studio.job.polling': { TR: 'Durum backend job servisinden düzenli olarak güncelleniyor.', EN: 'Status is updated regularly by the backend job service.' },
  'studio.export.copied': { TR: 'Bağlantı kopyalandı!', EN: 'Link copied!' },
  'studio.export.vip_title': { TR: 'VIP ile daha fazlası', EN: 'Get more with VIP' },
  'studio.export.vip_desc': { TR: 'Filigransız ve 1080p kalitesinde export al.', EN: 'Export without a watermark in 1080p quality.' },
  'studio.export.upgrade': { TR: 'Geçiş Yap', EN: 'Upgrade' },
  'upload.unsupported': { TR: 'Desteklenmeyen format. MP4, MOV veya WEBM seçin.', EN: 'Unsupported format. Choose MP4, MOV, or WEBM.' },
  'upload.empty': { TR: 'Boş video dosyası yüklenemez.', EN: 'An empty video file cannot be uploaded.' },
  'upload.max_size': { TR: 'Video en fazla {size} MB olabilir.', EN: 'The video can be up to {size} MB.' },
  'upload.aria': { TR: 'Yüklenecek video dosyasını seç', EN: 'Choose a video file to upload' },
  'upload.drop': { TR: 'Videoyu bırak, başlayalım', EN: "Drop the video and let's begin" },
  'upload.drag': { TR: 'Videonu buraya sürükle', EN: 'Drag your video here' },
  'upload.click': { TR: 'veya bilgisayarından seçmek için tıkla', EN: 'or click to choose from your computer' },
  'upload.max': { TR: 'En fazla', EN: 'Up to' },
  'upload.seconds': { TR: 'sn', EN: 'sec' },
  'templates.load_error': { TR: 'Hazır sahneler yüklenemedi.', EN: 'Ready scenes could not be loaded.' },
  'templates.loading': { TR: 'Hazır sahneler yükleniyor…', EN: 'Loading ready scenes…' },
  'templates.open_error': { TR: 'Sahne kataloğu açılamadı', EN: 'Scene catalog could not be opened' },
  'templates.retry': { TR: 'Tekrar dene', EN: 'Try again' },
  'templates.empty': { TR: 'Henüz hazır sahne yok', EN: 'No ready scenes yet' },
  'templates.empty_hint': { TR: 'Kendi videonu yükleyerek dublaj akışına devam edebilirsin.', EN: 'Upload your own video to continue the dubbing flow.' },
  'templates.all': { TR: 'Tümü', EN: 'All' },
  'templates.search': { TR: 'Sahne ara...', EN: 'Search scenes...' },
  'templates.popular': { TR: 'Popüler', EN: 'Popular' },
  'templates.shortest': { TR: 'En Kısa', EN: 'Shortest' },
  'templates.no_results': { TR: 'Bu kategoride sahne bulunamadı.', EN: 'No scenes were found in this category.' },
  'templates.demo': { TR: 'Demo', EN: 'Demo' },
  'templates.selected': { TR: 'Seçili', EN: 'Selected' },
  'templates.details': { TR: 'Detayları gör', EN: 'View details' },
  'templates.easy': { TR: 'Kolay', EN: 'Easy' },
  'templates.medium': { TR: 'Orta', EN: 'Medium' },
  'timeline.default_line': { TR: '{number}. repliğini buraya yaz.', EN: 'Write line {number} here.' },
  'timeline.duration_error': { TR: 'Replik bitiş zamanı video süresini aşıyor. Lütfen son repliği video bitişinden önce tamamlayın.', EN: 'A line ends after the video. Make sure the final line ends before the video does.' },
  'timeline.locked': { TR: 'Video işlenirken düzenleme geçici olarak kilitlenir.', EN: 'Editing is temporarily locked while the video is processed.' },
  'timeline.stop_active': { TR: 'Devam etmek için aktif kaydı durdurun.', EN: 'Stop the active recording to continue.' },
  'timeline.fix_lines': { TR: '{count} repliğin metnini veya zaman aralığını düzeltin.', EN: 'Fix the text or time range for {count} line(s).' },
  'timeline.record_more': { TR: 'Export için {count} repliği daha kaydedin.', EN: 'Record {count} more line(s) before exporting.' },
  'timeline.unsupported': { TR: 'Tarayıcınız mikrofon kaydını desteklemiyor. Güncel Chrome, Edge veya Safari kullanın.', EN: 'Your browser does not support microphone recording. Use a current version of Chrome, Edge, or Safari.' },
  'timeline.check_line': { TR: 'Replik metnini ve zaman aralığını kontrol edin.', EN: 'Check the line text and time range.' },
  'timeline.permission_denied': { TR: 'Mikrofon izni reddedildi. Adres çubuğundaki kilit simgesinden mikrofon iznini açıp tekrar deneyin.', EN: 'Microphone permission was denied. Allow microphone access from the lock icon in the address bar and try again.' },
  'timeline.no_microphone': { TR: 'Kullanılabilir mikrofon bulunamadı. Mikrofon bağlantısını ve Windows ses ayarlarını kontrol edin.', EN: 'No microphone was found. Check the microphone connection and your system sound settings.' },
  'timeline.microphone_busy': { TR: 'Mikrofon başka bir uygulama tarafından kullanılıyor. Diğer uygulamayı kapatıp tekrar deneyin.', EN: 'The microphone is being used by another application. Close it and try again.' },
  'timeline.microphone_error': { TR: 'Mikrofon açılamadı. Tarayıcı iznini ve ses aygıtını kontrol edip tekrar deneyin.', EN: 'The microphone could not be opened. Check browser permissions and the audio device, then try again.' },
  'timeline.max_lines': { TR: 'En fazla 20 replik ekleyebilirsiniz.', EN: 'You can add up to 20 lines.' },
  'timeline.new_line': { TR: 'Yeni replik', EN: 'New line' },
  'timeline.check_all': { TR: 'Tüm replik metinlerini ve zaman aralıklarını kontrol edin.', EN: 'Check all line texts and time ranges.' },
  'timeline.record_all': { TR: 'Videoyu oluşturmadan önce her repliği kaydedin.', EN: 'Record every line before creating the video.' },
  'timeline.title': { TR: 'Replik zaman çizelgesi', EN: 'Line timeline' },
  'timeline.subtitle': { TR: 'Her repliği kendi zaman aralığında seslendir.', EN: 'Record each line within its time range.' },
  'timeline.add': { TR: 'Replik ekle', EN: 'Add line' },
  'timeline.progress': { TR: 'Kayıt ilerlemesi', EN: 'Recording progress' },
  'timeline.completed': { TR: '{done}/{total} tamamlandı', EN: '{done}/{total} completed' },
  'timeline.demo_title': { TR: 'Demo medya yakında.', EN: 'Demo media coming soon.' },
  'timeline.demo_hint': { TR: 'Hazır replikleri düzenleyip kayıt akışını deneyebilirsin. Video önizleme ve MP4 export için kendi videonu yükle.', EN: 'Edit the prepared lines and try the recording flow. Upload your own video for video preview and MP4 export.' },
  'timeline.recording': { TR: 'Kayıt devam ediyor', EN: 'Recording in progress' },
  'timeline.recorded': { TR: 'Kayıt tamamlandı', EN: 'Recording complete' },
  'timeline.waiting': { TR: 'Kayıt bekliyor', EN: 'Waiting for recording' },
  'timeline.preview': { TR: 'Sahneyi oynat', EN: 'Play scene' },
  'timeline.delete': { TR: 'Repliği sil', EN: 'Delete line' },
  'timeline.text_aria': { TR: 'Replik {number} metni', EN: 'Line {number} text' },
  'timeline.start': { TR: 'Başlangıç', EN: 'Start' },
  'timeline.end': { TR: 'Bitiş', EN: 'End' },
  'timeline.invalid': { TR: 'Metin boş olmamalı; bitiş, başlangıçtan sonra ve video süresi içinde olmalı.', EN: 'Text cannot be empty; the end must be after the start and within the video duration.' },
  'timeline.stop': { TR: 'Kaydı durdur', EN: 'Stop recording' },
  'timeline.rerecord': { TR: 'Yeniden kaydet', EN: 'Record again' },
  'timeline.start_recording': { TR: 'Kaydı başlat', EN: 'Start recording' },
  'timeline.auto_stop': { TR: 'Süre bitince otomatik durur', EN: 'Stops automatically when time runs out' },
  'timeline.mute': { TR: 'Orijinal sesi tamamen kapat', EN: 'Mute original audio completely' },
  'timeline.subtitles': { TR: 'Altyazıları videoya göm', EN: 'Burn subtitles into the video' },
  'timeline.create': { TR: 'Kendi Sesimle Videoyu Oluştur', EN: 'Create Video with My Voice' },
  'timeline.ready': { TR: 'Tüm replikler hazır; videonu oluşturabilirsin.', EN: 'All lines are ready; you can create your video.' },
  'demo_scenes.title': { TR: 'Örnek Sahneler (Demo)', EN: 'Sample Scenes (Demo)' },
  'demo_scenes.cta': { TR: 'Hemen Dublajla', EN: 'Dub This Scene' },
  'ethics.title': { TR: 'Etik ve telif bilinci', EN: 'Ethics and copyright awareness' },
  'ethics.description': { TR: 'Bu uygulama eğlence, parodi ve portföy amaçlıdır. Gerçek kişileri taklit etmek, yanıltıcı içerik üretmek veya telifli içerikleri izinsiz dağıtmak kullanıcının sorumluluğundadır. Mikrofon kayıtları yalnızca video işlenirken kullanılır ve işlem sonrası geçici sunucu kopyaları silinir.', EN: 'This application is intended for entertainment, parody, and portfolio use. Users are responsible for avoiding impersonation, misleading content, and unauthorized distribution of copyrighted material. Microphone recordings are used only while processing the video, and temporary server copies are deleted afterward.' },
  'voice.title': { TR: 'Ses stili', EN: 'Voice style' },
  'voice.announcer': { TR: 'Spiker', EN: 'Announcer' },
  'voice.announcer_desc': { TR: 'Net ve güvenli', EN: 'Clear and confident' },
  'voice.robot': { TR: 'Robot', EN: 'Robot' },
  'voice.robot_desc': { TR: 'Mekanik ve ağır', EN: 'Mechanical and deep' },
  'voice.dramatic': { TR: 'Dramatik', EN: 'Dramatic' },
  'voice.dramatic_desc': { TR: 'Vurgulu anlatım', EN: 'Expressive delivery' },
  'voice.documentary': { TR: 'Belgesel', EN: 'Documentary' },
  'voice.documentary_desc': { TR: 'Sakin ve meraklı', EN: 'Calm and curious' },
  'voice.energetic': { TR: 'Enerjik', EN: 'Energetic' },
  'voice.energetic_desc': { TR: 'Hızlı ve canlı', EN: 'Fast and lively' },
  'job.failed': { TR: 'Video oluşturulamadı', EN: 'Video could not be created' },
  'dubs.title': { TR: 'Dublajlar', EN: 'Dubs' },
  'dubs.description': { TR: 'Topluluğun kaydettiği efsane dublajları keşfet.', EN: 'Discover memorable dubs recorded by the community.' },
  'dubs.demo_notice': { TR: 'Henüz gerçek dublaj yok. Aşağıdaki içerikler Demo amaçlı listelenmektedir.', EN: 'There are no public dubs yet. The content below is listed for demo purposes.' },
  'dubs.like_login': { TR: 'Beğenmek için giriş yapmalısınız.', EN: 'You need to log in to like a dub.' },
  'dubs.action_failed': { TR: 'İşlem başarısız.', EN: 'The action failed.' },
  'dubs.preparing': { TR: 'Video hazırlanıyor...', EN: 'Preparing video...' },
  'dubs.report': { TR: 'İçeriği Raporla', EN: 'Report content' },
  'dubs.views': { TR: 'İzlenme Sayısı', EN: 'View count' },
  'dubs.unlike': { TR: 'Beğeniyi Geri Al', EN: 'Remove like' },
  'dubs.like': { TR: 'Beğen', EN: 'Like' },
  'dubs.comments': { TR: 'Yorumlar', EN: 'Comments' },
  'dubs.download': { TR: 'İndir', EN: 'Download' },
  'dubs.comedy': { TR: 'Komedi', EN: 'Comedy' },
  'comments.load_error': { TR: 'Yorumlar yüklenirken hata oluştu.', EN: 'Comments could not be loaded.' },
  'comments.added': { TR: 'Yorumunuz eklendi.', EN: 'Your comment was added.' },
  'comments.add_error': { TR: 'Yorum eklenemedi (1-500 karakter olmalı).', EN: 'Comment could not be added (must be 1-500 characters).' },
  'comments.delete_confirm': { TR: 'Yorumunuzu silmek istiyor musunuz?', EN: 'Do you want to delete your comment?' },
  'comments.deleted': { TR: 'Yorum silindi.', EN: 'Comment deleted.' },
  'comments.delete_error': { TR: 'Yorum silinemedi.', EN: 'Comment could not be deleted.' },
  'comments.loading': { TR: 'Yükleniyor...', EN: 'Loading...' },
  'comments.empty': { TR: 'İlk yorumu sen yaz!', EN: 'Write the first comment!' },
  'comments.delete': { TR: 'Sil', EN: 'Delete' },
  'comments.placeholder': { TR: 'Yorumunuz (En fazla 500 karakter)', EN: 'Your comment (up to 500 characters)' },
  'comments.send': { TR: 'Gönder', EN: 'Send' },
  'comments.login_prefix': { TR: 'Yorum yazmak için', EN: 'To write a comment,' },
  'comments.login': { TR: 'giriş yapın', EN: 'log in' },
  'membership.hero': { TR: 'Daha yüksek kalite, daha fazla yaratıcı araç.', EN: 'Higher quality, more creative tools.' },
  'membership.hero_desc': { TR: 'Ücretsiz planda kendi sesinle dublaj yapmaya devam et. VIP ile 1080p export ve opsiyonel AI ses modunu aç.', EN: 'Keep dubbing with your own voice on the Free plan. Unlock 1080p export and optional AI voice with VIP.' },
  'membership.free': { TR: 'Ücretsiz', EN: 'Free' },
  'membership.free_title': { TR: 'Başlamak için yeterli', EN: 'Everything you need to start' },
  'membership.free_desc': { TR: 'Video yükle, repliklerini mikrofonla kaydet, altyazılı MP4 çıktını al.', EN: 'Upload a video, record your lines, and export a subtitled MP4.' },
  'membership.current': { TR: 'Mevcut planın', EN: 'Your current plan' },
  'membership.days': { TR: '30 günlük erişim', EN: '30-day access' },
  'membership.vip_desc': { TR: '1080p çıktı ve AI ses araçları backend tarafından hesabına özel açılır.', EN: '1080p export and AI voice tools are securely enabled for your account by the backend.' },
  'membership.period': { TR: '/ 30 gün', EN: '/ 30 days' },
  'membership.ai_mode': { TR: 'AI sesle dublaj modu', EN: 'AI voice dubbing mode' },
  'membership.badge': { TR: 'Profil ve menüde VIP rozeti', EN: 'VIP badge in your profile and menu' },
  'membership.active': { TR: 'VIP üyeliğin aktif', EN: 'Your VIP membership is active' },
  'membership.buy': { TR: 'VIP üyelik al', EN: 'Get VIP membership' },
  'membership.feature': { TR: 'Özellik', EN: 'Feature' },
  'membership.included': { TR: 'Dahil', EN: 'Included' },
  'membership.locked': { TR: 'Kilitli', EN: 'Locked' },
  'membership.feature.mic': { TR: 'Kendi mikrofonunla dublaj', EN: 'Dub with your microphone' },
  'membership.feature.upload': { TR: 'Hazır sahne ve video yükleme', EN: 'Ready scenes and video uploads' },
  'membership.feature.quality': { TR: 'MP4 export kalitesi', EN: 'MP4 export quality' },
  'membership.feature.ai': { TR: 'AI sesle dublaj', EN: 'AI voice dubbing' },
  'membership.feature.badge': { TR: 'Hesapta VIP rozeti', EN: 'VIP account badge' },
  'membership.secure': { TR: 'Güvenli yetkilendirme', EN: 'Secure authorization' },
  'membership.secure_desc': { TR: 'VIP kontrolü yalnız arayüzde değil backend’de yapılır. Ücretsiz bir hesap kilitli API’yi doğrudan çağıramaz.', EN: 'VIP access is enforced by the backend, not only by the interface. A Free account cannot call locked APIs directly.' },
  'membership.payment': { TR: 'Ödeme doğrulaması', EN: 'Payment verification' },
  'membership.payment_desc': { TR: 'Shopier ödemesi doğrulandıktan sonra hesabına süreli VIP erişimi tanımlanır. Kart bilgileri DublajLab’da tutulmaz.', EN: 'Time-limited VIP access is added after Shopier payment verification. DublajLab does not store card details.' },
  'membership.paid': { TR: 'Ödemeyi tamamladın mı?', EN: 'Completed your payment?' },
  'membership.refresh_desc': { TR: 'Doğrulama sonrasında üyelik durumunu yenileyebilirsin.', EN: 'Refresh your membership status after verification.' },
  'membership.refresh': { TR: 'Üyeliği yenile', EN: 'Refresh membership' },
  'membership.login_first': { TR: 'VIP üyelik almak için önce giriş yapın.', EN: 'Log in before purchasing VIP membership.' },
  'membership.payment_unavailable': { TR: 'Ödeme altyapısı yakında açılacak veya şu an kapalı.', EN: 'Payment infrastructure is not available yet or is currently disabled.' },
  'membership.payment_error': { TR: 'Ödeme başlatılamadı. Lütfen tekrar deneyin.', EN: 'Payment could not be started. Please try again.' },
  'membership.connection_error': { TR: 'Bağlantı hatası oluştu.', EN: 'A connection error occurred.' },
  'membership.vip_refreshed': { TR: 'VIP üyeliğiniz aktif. Özellikler açıldı.', EN: 'Your VIP membership is active. Features are unlocked.' },
  'membership.pending': { TR: 'Ödeme doğrulaması henüz tamamlanmamış görünüyor.', EN: 'Payment verification does not appear to be complete yet.' },
  'membership.refresh_error': { TR: 'Üyelik durumu yenilenemedi.', EN: 'Membership status could not be refreshed.' },
  'membership.order_created': { TR: 'Sipariş kaydınız oluşturuldu: {id}. (Ödeme altyapısı henüz yapılandırılmadı)', EN: 'Your order was created: {id}. (Payment infrastructure is not configured yet)' },
  'error.daily_title': { TR: 'Günlük demo limiti doldu', EN: 'Daily demo limit reached' },
  'error.daily_hint': { TR: 'Public demo kotası UTC gün başlangıcında yenilenir. Daha sonra tekrar deneyin.', EN: 'The public demo quota resets at the start of each UTC day. Try again later.' },
  'error.limit_title': { TR: 'Public demo limiti aşıldı', EN: 'Public demo limit exceeded' },
  'error.limit_hint': { TR: 'Daha küçük veya daha kısa bir video/kayıt seçip yeniden deneyin.', EN: 'Choose a smaller or shorter video/recording and try again.' },
  'error.backend_title': { TR: 'Backend bağlantısı kurulamadı', EN: 'Could not connect to the backend' },
  'error.backend_hint': { TR: 'Backend sunucusunun çalıştığını ve API adresinin doğru ayarlandığını kontrol edin.', EN: 'Check that the backend is running and the API address is configured correctly.' },
  'error.ffmpeg_title': { TR: 'Medya motoru hazır değil', EN: 'Media engine is not ready' },
  'error.ffmpeg_hint': { TR: 'FFmpeg kurulumunu ve PATH ayarını kontrol edin; ardından backend sunucusunu yeniden başlatın.', EN: 'Check the FFmpeg installation and PATH, then restart the backend server.' },
  'error.microphone_title': { TR: 'Mikrofon erişimi gerekli', EN: 'Microphone access is required' },
  'error.microphone_hint': { TR: 'Adres çubuğundaki kilit simgesinden mikrofon iznini açın ve kayıt düğmesine yeniden basın.', EN: 'Allow microphone access from the lock icon in the address bar, then press record again.' },
  'error.generic_title': { TR: 'İşlem tamamlanamadı', EN: 'The operation could not be completed' },
  'error.generic_hint': { TR: 'Bilgileri kontrol edip tekrar deneyin. Sorun sürerse sunucu hata kayıtlarını kontrol edin.', EN: 'Check the information and try again. If the issue continues, check the server error logs.' },
  'action.upload_error': { TR: 'Video yüklenirken bir hata oluştu.', EN: 'An error occurred while uploading the video.' },
  'action.retry_upload': { TR: 'Yüklemeyi tekrar dene', EN: 'Retry upload' },
  'action.template_file_error': { TR: 'Template video dosyası yüklenemedi. Dosya yolunu ve lisans metadata’sını kontrol edin.', EN: 'The template video could not be loaded. Check the file path and license metadata.' },
  'action.template_error': { TR: 'Hazır sahne açılamadı.', EN: 'The ready scene could not be opened.' },
  'action.export_preparing': { TR: 'Export isteği hazırlanıyor.', EN: 'Preparing export request.' },
  'action.export_ready': { TR: 'Dublaj videosu hazır.', EN: 'The dubbed video is ready.' },
  'action.saved': { TR: 'Dublajın hesabına kaydedildi.', EN: 'Your dub was saved to your account.' },
  'action.processing_error': { TR: 'Video işlenirken bir hata oluştu.', EN: 'An error occurred while processing the video.' },
  'action.no_output': { TR: 'Job tamamlandı ancak çıktı bağlantısı alınamadı.', EN: 'The job completed, but no output link was returned.' },
  'action.ai_vip': { TR: 'AI sesle dublaj VIP üyelere özeldir.', EN: 'AI voice dubbing is available to VIP members only.' },
  'action.upload_first': { TR: 'Önce bir video yükleyin.', EN: 'Upload a video first.' },
  'action.script_required': { TR: 'Dublaj metni boş bırakılamaz.', EN: 'The dubbing script cannot be empty.' },
  'action.template_export_unavailable': { TR: 'MP4 export için template video dosyasının projeye güvenli biçimde eklenmesi veya kendi videonun yüklenmesi gerekir.', EN: 'To export MP4, add the template video safely to the project or upload your own video.' },
  'action.tiktok_hint': { TR: 'Videonuzu indirip TikTok uygulamasından yükleyebilirsiniz.', EN: 'Download your video, then upload it from the TikTok app.' },
  'action.reels_hint': { TR: 'Videonuzu indirip Reels olarak paylaşabilirsiniz.', EN: 'Download your video, then share it as a Reel.' },
  'howto.title': { TR: 'Nasıl Oynanır?', EN: 'How Does It Work?' },
  'howto.description': { TR: "DublajLab'de kendi sesinle eğlenceli videolar üretmek çok kolay.", EN: 'Creating fun videos with your own voice is easy in DublajLab.' },
  'howto.step1': { TR: 'Sahne Seç', EN: 'Choose a Scene' },
  'howto.step1_desc': { TR: 'Sahneler galerisinden bir video seç veya kendi cihazından video yükle.', EN: 'Choose a video from the scene gallery or upload one from your device.' },
  'howto.step2': { TR: 'Repliği Oku', EN: 'Read the Line' },
  'howto.step2_desc': { TR: 'Zaman çizelgesindeki replikleri takip et, sıran geldiğinde mikrofonla sesini kaydet.', EN: 'Follow the lines on the timeline and record your voice when it is your turn.' },
  'howto.step3': { TR: 'Videoyu İndir', EN: 'Download the Video' },
  'howto.step3_desc': { TR: 'Tüm replikleri kaydettikten sonra sistem otomatik olarak sesi miksler ve MP4 olarak sana sunar.', EN: 'After you record every line, the system mixes the audio and creates an MP4 for you.' },
  'howto.start': { TR: 'Hemen Başla', EN: 'Get Started' },
  'daily.title': { TR: 'Günün Dublajı', EN: 'Daily Dub' },
  'daily.description': { TR: 'Bugün en çok güldüren performans.', EN: "Today's funniest performance." },
  'daily.demo': { TR: 'Demo İçerik', EN: 'Demo Content' },
  'daily.winner': { TR: 'Günün Kazananı', EN: "Today's Winner" },
  'daily.demo_title': { TR: 'Toplantı faciası (Demo)', EN: 'Meeting disaster (Demo)' },
  'daily.voice_by': { TR: 'Seslendiren', EN: 'Voiced by' },
  'daily.quote': { TR: '“Tüm gün süren o toplantı beş dakika sürecek dediler... Sonra herkes kahve molasına çıktı ama mikrofonum açık kalmış!”', EN: '“They said that all-day meeting would take five minutes... Then everyone went for coffee, but my microphone was still on!”' },
  'daily.watch': { TR: 'Dublajı İzle', EN: 'Watch the Dub' },
  'daily.create': { TR: 'Sen de Seslendir', EN: 'Record Your Version' },
  'daily.all': { TR: 'Tüm Dublajlar', EN: 'All Dubs' },
  'daily.notice': { TR: '* Yakında gerçek topluluk içerikleri eklenecektir. Bu sayfa tasarım demosudur.', EN: '* Real community content will be added soon. This page is a design demo.' },

  // Footer
  'footer.desc': { TR: 'Portföy ve teknoloji demosu.', EN: 'Portfolio and technology demo.' },
  'footer.links.product': { TR: 'Ürün', EN: 'Product' },
  'footer.links.play': { TR: 'Stüdyo', EN: 'Studio' },
  'footer.links.scenes': { TR: 'Hazır Sahneler', EN: 'Templates' },
  'footer.links.dubs': { TR: 'Topluluk', EN: 'Community' },
  'footer.links.daily': { TR: 'Günün Dublajı', EN: 'Daily Dub' },
  'footer.links.resources': { TR: 'Kaynaklar', EN: 'Resources' },
  'footer.links.howto': { TR: 'Nasıl Kullanılır?', EN: 'How to Use?' },
  'footer.links.legal': { TR: 'Yasal', EN: 'Legal' },
  'footer.links.privacy': { TR: 'Gizlilik', EN: 'Privacy' },
  'footer.links.terms': { TR: 'Kullanım Koşulları', EN: 'Terms of Use' },
  'footer.links.copyright': { TR: 'Telif Hakkı', EN: 'Copyright' },
  'footer.links.suggest': { TR: 'Sahne Öner', EN: 'Suggest Scene' },
  'footer.links.contact': { TR: 'İletişim', EN: 'Contact' },
  'footer.links.about': { TR: 'Hakkımızda', EN: 'About Us' },
  'footer.links.corporate': { TR: 'Kurumsal', EN: 'Corporate' },
  'toast.social_soon': { TR: 'DublajLab resmi sosyal medya hesabı yakında açılacak.', EN: 'DublajLab official social media account will be opened soon.' },
  'toast.suggest_soon': { TR: 'Sahne önerme özelliği yakında.', EN: 'Scene suggestion feature coming soon.' },
  'toast.contact_soon': { TR: 'İletişim paneli yakında.', EN: 'Contact panel coming soon.' },
  'social.soon': { TR: 'Resmi hesap yakında', EN: 'Official account soon' },
  // Legal Modal
  'legal.title': { TR: 'Yasal ve Kurumsal', EN: 'Legal & Corporate' },
  'legal.subtitle': { TR: 'Public Beta Bilgilendirmesi', EN: 'Public Beta Information' },
  'legal.close': { TR: 'Kapat', EN: 'Close' },
  
  'legal.about.title': { TR: 'Hakkımızda (Taslak)', EN: 'About Us (Draft)' },
  'legal.about.p1': { TR: 'DublajLab, kısa videolarınızı tarayıcı üzerinden kendi sesinizle dublajlamanızı sağlayan yaratıcı bir medya aracıdır.', EN: 'DublajLab is a creative media tool that allows you to dub your short videos with your own voice directly via the browser.' },
  'legal.about.p2': { TR: 'Bu platform şu an "Public Beta" aşamasındadır. Kullanıcıların yaratıcılıklarını sergilemeleri ve portföy içerikleri üretmeleri için tasarlanmıştır.', EN: 'This platform is currently in "Public Beta". It is designed for users to showcase their creativity and produce portfolio content.' },
  'legal.about.p3': { TR: 'Ekibimiz, video düzenleme süreçlerini olabildiğince basitleştirerek herkesin kendi sesinden hikayeler anlatabilmesini hedefliyor.', EN: 'Our team aims to simplify video editing processes as much as possible so that everyone can tell stories with their own voice.' },

  'legal.contact.title': { TR: 'İletişim (Taslak)', EN: 'Contact (Draft)' },
  'legal.contact.p1': { TR: 'DublajLab Public Beta süresince resmi destek kanallarımız sınırlıdır. Geri bildirimleriniz ve hata bildirimleriniz bizim için çok değerlidir.', EN: 'During the DublajLab Public Beta, our official support channels are limited. Your feedback and bug reports are very valuable to us.' },
  'legal.contact.p2': { TR: 'Bize aşağıdaki e-posta adresinden ulaşabilirsiniz:', EN: 'You can reach us at the following e-mail address:' },
  'legal.contact.p3': { TR: '* Sosyal medya hesaplarımız yakında aktif edilecektir.', EN: '* Our social media accounts will be activated soon.' },

  'legal.privacy.title': { TR: 'Gizlilik Politikası (Taslak)', EN: 'Privacy Policy (Draft)' },
  'legal.privacy.p1': { TR: 'DublajLab, kişisel verilerinizin güvenliğine önem verir. Bu metin Public Beta süreci için bir bilgilendirmedir.', EN: 'DublajLab cares about the security of your personal data. This text is an information for the Public Beta process.' },
  'legal.privacy.li1': { TR: 'Medya Verileri: Tarayıcı üzerinden kaydettiğiniz sesler sadece export işlemi için sunucuya iletilir ve işlem bittikten sonra geçici sunuculardan silinir.', EN: 'Media Data: The sounds you record via the browser are only transmitted to the server for export and are deleted from temporary servers after the process is finished.' },
  'legal.privacy.li2': { TR: 'Kalıcı Saklama: Üye olan kullanıcıların projeleri ve indirmeye hazır MP4 çıktıları sunucularımızda saklanır. Depolama temizlik politikalarımız (cleanup) eski dosyaları silebilir.', EN: 'Persistent Storage: The projects and ready-to-download MP4 outputs of registered users are stored on our servers. Our storage cleanup policies can delete old files.' },
  'legal.privacy.li3': { TR: 'Üçüncü Taraflar: Verileriniz izniniz olmadan üçüncü taraf reklam şirketlerine satılmaz. Sadece hizmeti sunmak için gereken bulut sağlayıcıları (örn. Cloudflare, Railway) kullanılır.', EN: 'Third Parties: Your data is not sold to third-party advertising companies without your permission. Only cloud providers (e.g. Cloudflare, Railway) required to provide the service are used.' },

  'legal.terms.title': { TR: 'Kullanım Koşulları (Taslak)', EN: 'Terms of Use (Draft)' },
  'legal.terms.p1': { TR: 'DublajLab hizmetlerini kullanarak aşağıdaki koşulları kabul etmiş sayılırsınız:', EN: 'By using DublajLab services, you are deemed to have accepted the following conditions:' },
  'legal.terms.li1': { TR: 'Kullanıcılar sisteme yükledikleri tüm video ve ses içeriklerinden bizzat sorumludur.', EN: 'Users are personally responsible for all video and audio content they upload to the system.' },
  'legal.terms.li2': { TR: 'Hizmet şu an "Public Beta" aşamasında olup, kesintiler veya veri kayıpları yaşanabilir.', EN: 'The service is currently in "Public Beta" and interruptions or data loss may occur.' },
  'legal.terms.li3': { TR: 'Kötüye kullanım (DDoS, API limitlerini aşma çabası) durumunda hesabınız veya IP adresiniz engellenebilir.', EN: 'In case of abuse (DDoS, effort to exceed API limits), your account or IP address may be blocked.' },

  'legal.copyright.title': { TR: 'Telif Bildirimi (Taslak)', EN: 'Copyright Notice (Draft)' },
  'legal.copyright.p1': { TR: 'DublajLab platformunda paylaşılan veya yüklenen içeriklerin fikri mülkiyet haklarına saygı duyuyoruz.', EN: 'We respect the intellectual property rights of the content shared or uploaded on the DublajLab platform.' },
  'legal.copyright.li1': { TR: 'Sadece kullanım hakkına sahip olduğunuz veya kamuya açık (CC0 vb.) videoları yükleyin.', EN: 'Only upload videos that you have the right to use or are public (CC0 etc.).' },
  'legal.copyright.li2': { TR: 'Gerçek kişilerin seslerini taklit etmek (deepfake) veya onları yanıltıcı durumlara sokmak yasaktır.', EN: 'Imitating the voices of real people (deepfake) or putting them in misleading situations is prohibited.' },
  'legal.copyright.li3': { TR: 'Eğer telif hakkına sahip olduğunuz bir materyalin izinsiz kullanıldığını düşünüyorsanız, iletişim kanallarımızdan bize bildirebilirsiniz. İçerik incelenip yayından kaldırılacaktır.', EN: 'If you think that a material you own the copyright is used without permission, you can report it to us via our communication channels. The content will be reviewed and removed.' },

  'legal.refund.title': { TR: 'İade ve İptal Koşulları (Taslak)', EN: 'Refund and Cancellation Policy (Draft)' },
  'legal.refund.p1': { TR: 'Not: Şu an sistemimizde Shopier ödeme entegrasyonu (VIP) aktif değildir. Aşağıdaki kurallar ödeme alındığında geçerli olacaktır.', EN: 'Note: Currently, Shopier payment integration (VIP) is not active in our system. The following rules will be valid when payment is received.' },
  'legal.refund.li1': { TR: 'Satın alınan VIP üyelikler dijital hizmet niteliğinde olduğundan, hizmet kullanılmaya başlandıktan sonra cayma hakkı kural olarak geçerli değildir.', EN: 'Since purchased VIP memberships are in the nature of digital services, the right of withdrawal is generally not valid after the service has started to be used.' },
  'legal.refund.li2': { TR: 'Teknik bir nedenden ötürü (sistemin sürekli çökmesi vb.) vaat edilen hizmet hiç verilememişse, destek talebi üzerinden iade incelenebilir.', EN: 'If the promised service cannot be provided at all due to a technical reason (constant system crash, etc.), a refund can be reviewed via a support request.' },

  'legal.distance.title': { TR: 'Mesafeli Satış Sözleşmesi (Taslak)', EN: 'Distance Selling Contract (Draft)' },
  'legal.distance.p1': { TR: 'Madde 1 - Taraflar: Bu sözleşme DublajLab (Satıcı) ile VIP/Premium hizmet alan kullanıcı (Alıcı) arasındadır. (Şu an test aşamasındadır, yasal satıcı ünvanı atanmamıştır).', EN: 'Article 1 - Parties: This contract is between DublajLab (Seller) and the user receiving VIP/Premium service (Buyer). (Currently in testing phase, legal seller title not assigned).' },
  'legal.distance.p2': { TR: 'Madde 2 - Konu: Sözleşmenin konusu, alıcının dijital VIP hizmeti satın alması ve bu hizmetin elektronik ortamda anında teslimidir.', EN: 'Article 2 - Subject: The subject of the contract is the buyer purchasing digital VIP service and immediate delivery of this service electronically.' },
  'legal.distance.p3': { TR: 'Madde 3 - Teslimat: Satın alım tamamlandıktan hemen sonra üyelik statüsü güncellenir ve yüksek çözünürlük gibi özellikler aktifleşir.', EN: 'Article 3 - Delivery: Immediately after the purchase is completed, the membership status is updated and features such as high resolution are activated.' },
  'legal.distance.p4': { TR: 'Not: Gerçek ticari faaliyet başladığında bu sayfa hukuk metni ile güncellenecektir.', EN: 'Note: When real commercial activity starts, this page will be updated with a legal text.' },

  'footer.links.refund': { TR: 'İade ve İptal', EN: 'Refund Policy' },
  'footer.links.distance': { TR: 'Mesafeli Satış', EN: 'Distance Selling' },
  'footer.links.oda_kur': { TR: 'Oda kur', EN: 'Create Room' },
  'footer.disclaimer': { TR: 'DublajLab kullanıcıların gönderdiği içeriklerde gerekli kullanım haklarına sahip olduklarını beyan etmelerini zorunlu tutar. Hak sahibinden geçerli bir ihlal bildirimi alınırsa içerik incelenir ve gerekirse erişimden kaldırılır.', EN: 'DublajLab requires users to declare that they have the necessary usage rights in the content they submit. If a valid infringement notice is received from the right holder, the content is reviewed and removed if necessary.' },

};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const storedLanguage = typeof window === 'undefined'
      ? null
      : window.localStorage.getItem('dublajlab-language');
    return storedLanguage === 'EN' ? 'EN' : 'TR';
  });

  useEffect(() => {
    window.localStorage.setItem('dublajlab-language', language);
    document.documentElement.lang = language === 'TR' ? 'tr' : 'en';
  }, [language]);

  const t = (key: string): string => {
    return translations[key]?.[language] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
