/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useEffect, useState, ReactNode } from 'react';

export type Language = 'TR' | 'EN';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<string, Record<Language, string>> = {
  // Navbar
  'nav.play': { TR: 'Oyna', EN: 'Play' },
  'nav.scenes': { TR: 'Sahneler', EN: 'Scenes' },
  'nav.dubs': { TR: 'Dublajlar', EN: 'Dubs' },
  'nav.daily': { TR: 'Günün Dublajı', EN: 'Daily Dub' },
  'nav.language': { TR: 'Dil', EN: 'Language' },
  'nav.login': { TR: 'Giriş Yap', EN: 'Login' },
  'nav.register': { TR: 'Kayıt Ol', EN: 'Sign Up' },
  'nav.moderation': { TR: 'Moderasyon', EN: 'Moderation' },
  'nav.system': { TR: 'Sistem (Ops)', EN: 'System (Ops)' },
  'nav.account_registered': { TR: 'Kayıtlı Hesap', EN: 'Registered Account' },
  'nav.level': { TR: 'Seviye 1', EN: 'Level 1' },
  'nav.account_section': { TR: 'Hesabın', EN: 'Your account' },
  'nav.vip_active': { TR: 'VIP Aktif', EN: 'VIP Active' },
  'nav.vip_join': { TR: 'VIP ol', EN: 'Go VIP' },
  'nav.vip_active_desc': { TR: '1080p ve AI ses özelliklerin açık.', EN: '1080p and AI voice features are enabled.' },
  'nav.vip_join_desc': { TR: '1080p çıktı ve AI ses modunu aç.', EN: 'Unlock 1080p export and AI voice mode.' },
  'nav.moderation_panel': { TR: 'Moderasyon Paneli', EN: 'Moderation Panel' },
  'nav.system_status': { TR: 'Sistem Durumu (Ops)', EN: 'System Status (Ops)' },
  'drop.profile': { TR: 'Profilim', EN: 'My Profile' },
  'drop.membership': { TR: 'Üyeliğim', EN: 'Membership' },
  'drop.library': { TR: 'Kataloğum', EN: 'My Library' },
  'drop.scenes': { TR: 'Sahnelerim', EN: 'My Scenes' },
  'drop.favorites': { TR: 'Favorilerim', EN: 'Favorites' },
  'drop.credits': { TR: 'Kredilerim', EN: 'My Credits' },
  'drop.account': { TR: 'Hesabım', EN: 'Settings' },
  'drop.logout': { TR: 'Çıkış Yap', EN: 'Logout' },
  
  // Account Settings
  'account.title': { TR: 'Hesap Ayarları', EN: 'Account Settings' },
  'account.save': { TR: 'Tümünü kaydet', EN: 'Save all' },
  'account.discord_link': { TR: 'Discord Hesabını Bağla', EN: 'Link Discord Account' },
  'account.discord_linked': { TR: 'Discord Bağlandı', EN: 'Discord Linked' },
  'account.delete': { TR: 'Hesabımı silmek istiyorum', EN: 'I want to delete my account' },

  // Membership & Credits
  'vip.button': { TR: 'Şimdi VIP Ol', EN: 'Become VIP Now' },
  'credits.buy': { TR: 'Kredi Al', EN: 'Buy Credits' },

  // Auth Page
  'auth.hero.title1': { TR: 'Kendi sesinle', EN: 'Take the stage' },
  'auth.hero.title2': { TR: 'sahnede yerini al.', EN: 'with your own voice.' },
  'auth.hero.desc': { TR: 'Favori filmlerine, popüler dizilere ve viral videolara kendi sesinle dublaj yap. Arkadaşlarınla paylaş veya toplulukta öne çık.', EN: 'Dub your favorite movies, popular series, and viral videos with your own voice. Share with friends or stand out in the community.' },
  'auth.login.title': { TR: 'Tekrar Hoş Geldin', EN: 'Welcome Back' },
  'auth.login.desc': { TR: 'Kaldığın yerden devam etmek için giriş yap.', EN: 'Log in to continue where you left off.' },
  'auth.register.title': { TR: 'Maceraya Katıl', EN: 'Join the Adventure' },
  'auth.register.desc': { TR: 'Ücretsiz hesabını oluştur ve ilk dublajını yap.', EN: 'Create your free account and make your first dub.' },
  'auth.feature.scenes': { TR: 'Popüler Sahneler', EN: 'Popular Scenes' },
  'auth.feature.ai_mix': { TR: 'AI Destekli Mix', EN: 'AI-assisted Mix' },
  'auth.quote.1': { TR: '"Senin sorunun ne biliyor musun?"', EN: '"Do you know what your problem is?"' },
  'auth.quote.2': { TR: '"Hadi oradan!"', EN: '"Oh, come on!"' },
  'auth.quote.3': { TR: '"Ben de tam onu diyecektim."', EN: '"I was just about to say that."' },
  'auth.quote.4': { TR: '"Sessizlik!"', EN: '"Silence!"' },
  'auth.username': { TR: 'Kullanıcı Adı', EN: 'Username' },
  'auth.email': { TR: 'E-posta Adresi', EN: 'Email Address' },
  'auth.password': { TR: 'Şifre', EN: 'Password' },
  'auth.waiting': { TR: 'Bekleniyor...', EN: 'Please wait...' },
  'auth.login.action': { TR: 'Giriş Yap', EN: 'Log In' },
  'auth.register.action': { TR: 'Hesap Oluştur', EN: 'Create Account' },
  'auth.or': { TR: 'veya', EN: 'or' },
  'auth.no_account': { TR: 'Hesabın yok mu?', EN: "Don't have an account?" },
  'auth.have_account': { TR: 'Zaten hesabın var mı?', EN: 'Already have an account?' },
  'auth.signup_link': { TR: 'Kayıt ol', EN: 'Sign up' },
  'auth.login_link': { TR: 'Giriş yap', EN: 'Log in' },
  'auth.register_success': { TR: 'Kayıt başarılı! Lütfen giriş yapın.', EN: 'Registration successful! Please log in.' },
  'auth.login_success': { TR: 'Giriş başarılı! Stüdyoya yönlendiriliyorsunuz.', EN: 'Login successful! Taking you to the studio.' },
  'auth.generic_error': { TR: 'Bir hata oluştu.', EN: 'Something went wrong.' },

  // Studio
  'studio.badge': { TR: 'Tarayıcı tabanlı dublaj stüdyosu', EN: 'Browser-based dubbing studio' },
  'studio.hero.line1': { TR: 'Kendi sesinle komik', EN: 'Create funny dubbed' },
  'studio.hero.accent': { TR: 'dublaj videoları', EN: 'dubbed videos' },
  'studio.hero.line2': { TR: 'oluştur', EN: 'with your voice' },
  'studio.hero.description': { TR: 'Hazır sahne seç ya da kendi videonu yükle, repliği oku, altyazılı MP4 olarak indir.', EN: 'Choose a ready-made scene or upload your own video, read the lines, and download a subtitled MP4.' },
  'studio.cta.start': { TR: 'Hemen Dublaj Yap', EN: 'Start Dubbing' },
  'studio.cta.templates': { TR: 'Hazır Sahneleri Keşfet', EN: 'Explore Ready Scenes' },
  'studio.trust.own_video': { TR: 'Kendi videonu kullan', EN: 'Use your own video' },
  'studio.trust.no_copyright': { TR: 'Telifli içerik yükleme', EN: 'Do not upload copyrighted content' },
  'studio.trust.no_impersonation': { TR: 'Kimseyi taklit etme', EN: 'Do not impersonate anyone' },
  'studio.step.source': { TR: 'Sahneyi seç', EN: 'Choose a scene' },
  'studio.step.record': { TR: 'Replikleri kaydet', EN: 'Record the lines' },
  'studio.step.download': { TR: 'MP4’ü indir', EN: 'Download MP4' },
  'studio.preview.title': { TR: 'Çıktı örneği', EN: 'Output preview' },
  'studio.preview.subtitle': { TR: 'Repliğini oku → MP4 indir', EN: 'Read your line → download MP4' },
  'studio.preview.line1': { TR: 'Toplantı beş dakika sürecek dediler…', EN: 'They said the meeting would take five minutes…' },
  'studio.preview.line2': { TR: 'Tüm gün süren o toplantı…', EN: 'That meeting lasted all day…' },
  'studio.preview.line3': { TR: 'Neyse, kahve molası…', EN: 'Anyway, coffee break…' },
  'studio.feature.voice': { TR: 'Kendi sesim', EN: 'My own voice' },
  'studio.feature.timeline': { TR: 'Timeline replik', EN: 'Timeline-based lines' },
  'studio.feature.export': { TR: 'MP4 export', EN: 'MP4 export' },
  'studio.feature.subtitles': { TR: 'Altyazı gömme', EN: 'Burned-in subtitles' },
  'studio.feature.copyright': { TR: 'Telif bilinci', EN: 'Copyright awareness' },
  'studio.demo.title': { TR: 'Public demo sınırları etkin', EN: 'Public demo limits are active' },
  'studio.demo.limits': { TR: 'En fazla {size} MB / {duration} saniye video, replik başına {recording} MB kayıt ve IP başına günde {exports} export kullanılabilir.', EN: 'You can use videos up to {size} MB / {duration} seconds, recordings up to {recording} MB per line, and {exports} exports per IP each day.' },
  'studio.demo.retention': { TR: 'Bu public demo dosyalarınızı kalıcı olarak saklamaz. Medya temizleme politikası {hours} saatliktir.', EN: 'This public demo does not store your files permanently. Media is cleaned up after {hours} hours.' },
  'studio.source.eyebrow': { TR: '01 / Kaynak video', EN: '01 / Source video' },
  'studio.source.title': { TR: 'Sahneni seç', EN: 'Choose your scene' },
  'studio.source.change': { TR: 'Kaynağı değiştir', EN: 'Change source' },
  'studio.source.upload': { TR: 'Kendi videonu yükle', EN: 'Upload your video' },
  'studio.source.template': { TR: 'Hazır sahne seç', EN: 'Choose a ready scene' },
  'studio.video.validating': { TR: 'Video doğrulanıyor', EN: 'Validating video' },
  'studio.video.checking': { TR: 'Süre ve format kontrol ediliyor…', EN: 'Checking duration and format…' },
  'studio.video.ready': { TR: 'Video kullanıma hazır', EN: 'Video is ready' },
  'studio.editor.eyebrow': { TR: '02 / Dublaj stüdyosu', EN: '02 / Dubbing studio' },
  'studio.editor.title': { TR: 'Sahneyi seslendir', EN: 'Dub the scene' },
  'studio.plan.free': { TR: 'Ücretsiz · 720p export', EN: 'Free · 720p export' },
  'studio.plan.vip': { TR: 'VIP · 1080p export', EN: 'VIP · 1080p export' },
  'studio.mode.voice': { TR: 'Kendi sesim', EN: 'My voice' },
  'studio.mode.ai': { TR: 'AI ses · VIP', EN: 'AI voice · VIP' },
  'studio.empty.title': { TR: 'Önce bir kaynak seç', EN: 'Choose a source first' },
  'studio.empty.description': { TR: 'Hazır sahne seçtiğinde veya videonu yüklediğinde replik zaman çizelgesi burada oluşacak.', EN: 'Your line timeline will appear here after you choose a ready scene or upload a video.' },
  'studio.empty.upload': { TR: 'Video yükle', EN: 'Upload video' },
  'studio.catalog.title': { TR: 'Sahne Kataloğu', EN: 'Scene Catalog' },
  'studio.catalog.description': { TR: 'Dublaj yapmak için popüler bir sahne seç veya doğrudan projeye başla.', EN: 'Choose a popular scene to dub or start a project directly.' },
  'studio.auth_required': { TR: 'Lütfen giriş yapın.', EN: 'Please log in.' },
  'studio.unauthorized': { TR: 'Bu sayfaya erişim yetkiniz yok.', EN: 'You do not have permission to access this page.' },
  'studio.export.ready': { TR: '03 / Export hazır', EN: '03 / Export ready' },
  'studio.export.title': { TR: 'Dublajın paylaşılmaya hazır.', EN: 'Your dub is ready to share.' },
  'studio.export.download': { TR: 'MP4 indir', EN: 'Download MP4' },
  'studio.export.next': { TR: 'Sırada ne var?', EN: "What's next?" },
  'studio.export.description': { TR: 'Sonucu indirebilir, sosyal medyada paylaşabilir veya yeni projeye başlayabilirsin.', EN: 'Download the result, share it on social media, or start a new project.' },
  'studio.export.copy': { TR: 'Linki Kopyala', EN: 'Copy Link' },
  'studio.export.share_x': { TR: "X'te Paylaş", EN: 'Share on X' },
  'studio.export.share_text': { TR: 'Dublajım hazır!', EN: 'My dub is ready!' },
  'studio.export.same_video': { TR: 'Aynı video ile dene', EN: 'Try the same video' },
  'studio.export.new_video': { TR: 'Yeni video', EN: 'New video' },
  'studio.template.media_soon': { TR: 'Demo medya yakında', EN: 'Demo media coming soon' },
  'studio.template.media_hint': { TR: 'Replikleri düzenle ve mikrofon kayıt akışını dene. Kendi videonu bağlayarak tam export alabilirsin.', EN: 'Edit the lines and try the microphone recording flow. Add your own video for a complete export.' },
  'studio.template.license': { TR: 'Lisans', EN: 'License' },
  'studio.template.source': { TR: 'Kaynak', EN: 'Source' },
  'studio.template.seconds': { TR: 'sn', EN: 'sec' },
  'studio.template.lines': { TR: 'replik', EN: 'lines' },
  'studio.ai.vip_only': { TR: 'AI ses modu VIP üyelere özeldir.', EN: 'AI voice mode is available to VIP members only.' },
  'studio.ai.login_vip': { TR: 'AI ses modu için giriş yapıp VIP üyeliği etkinleştirin.', EN: 'Log in and activate VIP membership to use AI voice mode.' },
  'studio.lipsync.title': { TR: 'Dudak Senkronizasyonu (Deneysel)', EN: 'Lip Sync (Experimental)' },
  'studio.lipsync.description': { TR: 'Yüz hareketlerini dublaj sesine göre işler', EN: 'Matches facial movement to the dubbed audio' },
  'studio.lipsync.vip_required': { TR: 'VIP üyelik gerektirir', EN: 'VIP membership required' },
  'studio.lipsync.vip_only': { TR: 'Yalnızca aktif VIP üyeler kullanabilir.', EN: 'Available only to active VIP members.' },
  'studio.ai.vip_title': { TR: 'AI ses modu VIP özelliğidir', EN: 'AI voice mode is a VIP feature' },
  'studio.ai.vip_description': { TR: 'Kendi sesinle dublaj ücretsizdir. AI ses ve 1080p export için VIP üyeliğini etkinleştir.', EN: 'Dubbing with your own voice is free. Activate VIP for AI voice and 1080p export.' },
  'studio.ai.vip_cta': { TR: 'VIP özelliklerini gör', EN: 'View VIP features' },
  'studio.ai.notice': { TR: 'Opsiyonel mod: Yazdığın metin, gerçek kişileri taklit etmeyen hazır bir Türkçe yapay sesle okunur.', EN: 'Optional mode: Your text is read with a preset synthetic voice that does not imitate a real person.' },
  'studio.ai.script': { TR: 'Dublaj metni', EN: 'Dubbing script' },
  'studio.ai.placeholder': { TR: 'Örn: Toplantı beş dakika sürecek dediklerinde ben…', EN: 'Example: When they said the meeting would take five minutes…' },
  'studio.ai.mute': { TR: 'Orijinal sesi kıs', EN: 'Lower original audio' },
  'studio.ai.mute_desc': { TR: 'AI dublajı öne çıkarır', EN: 'Makes the AI dub easier to hear' },
  'studio.ai.subtitles': { TR: 'Altyazıyı göm', EN: 'Burn in subtitles' },
  'studio.ai.subtitles_desc': { TR: 'Metni videoda gösterir', EN: 'Shows the text in the video' },
  'studio.ai.create': { TR: 'AI Sesle Video Oluştur', EN: 'Create Video with AI Voice' },
  'studio.ai.write_first': { TR: 'Devam etmek için dublaj metnini yazın.', EN: 'Enter the dubbing script to continue.' },
  'studio.job.status': { TR: 'Gerçek job durumu', EN: 'Live job status' },
  'studio.job.queued': { TR: 'Export sırasına alınıyor…', EN: 'Export is being queued…' },
  'studio.job.polling': { TR: 'Durum backend job servisinden düzenli olarak güncelleniyor.', EN: 'Status is updated regularly by the backend job service.' },
  'studio.job.ai_audio': { TR: 'AI ses hazırlanıyor.', EN: 'Preparing AI voice…' },
  'studio.job.recordings_validated': { TR: 'Ses kayıtları doğrulandı.', EN: 'Audio recordings validated…' },
  'studio.job.face_analysis': { TR: 'Yüz analiz ediliyor…', EN: 'Analyzing the face…' },
  'studio.job.lipsync': { TR: 'Dudak senkronizasyonu uygulanıyor…', EN: 'Applying lip sync…' },
  'studio.job.subtitles': { TR: 'Altyazılar hazırlanıyor…', EN: 'Preparing subtitles…' },
  'studio.job.mixing': { TR: 'Video, ses ve altyazı birleştiriliyor…', EN: 'Mixing video, audio, and subtitles…' },
  'studio.job.timeline': { TR: 'Kayıtlar zaman çizelgesine yerleştiriliyor…', EN: 'Placing recordings on the timeline…' },
  'studio.job.saving': { TR: 'MP4 çıktısı kaydediliyor…', EN: 'Saving the MP4 output…' },
  'studio.job.processing': { TR: 'Video işleniyor…', EN: 'Processing the video…' },
  'studio.export.copied': { TR: 'Bağlantı kopyalandı!', EN: 'Link copied!' },
  'studio.export.vip_title': { TR: 'VIP ile daha fazlası', EN: 'Get more with VIP' },
  'studio.export.vip_desc': { TR: 'Filigransız ve 1080p kalitesinde export al.', EN: 'Export without a watermark in 1080p quality.' },
  'studio.export.upgrade': { TR: 'Geçiş Yap', EN: 'Upgrade' },
  'upload.unsupported': { TR: 'Desteklenmeyen format. MP4, MOV veya WEBM seçin.', EN: 'Unsupported format. Choose MP4, MOV, or WEBM.' },
  'upload.empty': { TR: 'Boş video dosyası yüklenemez.', EN: 'An empty video file cannot be uploaded.' },
  'upload.max_size': { TR: 'Video en fazla {size} MB olabilir.', EN: 'The video can be up to {size} MB.' },
  'upload.aria': { TR: 'Yüklenecek video dosyasını seç', EN: 'Choose a video file to upload' },
  'upload.drop': { TR: 'Videoyu bırak, başlayalım', EN: "Drop the video and let's begin" },
  'upload.drag': { TR: 'Videonu buraya sürükle', EN: 'Drag your video here' },
  'upload.click': { TR: 'veya bilgisayarından seçmek için tıkla', EN: 'or click to choose from your computer' },
  'upload.max': { TR: 'En fazla', EN: 'Up to' },
  'upload.seconds': { TR: 'sn', EN: 'sec' },
  'templates.load_error': { TR: 'Hazır sahneler yüklenemedi.', EN: 'Ready scenes could not be loaded.' },
  'templates.loading': { TR: 'Hazır sahneler yükleniyor…', EN: 'Loading ready scenes…' },
  'templates.open_error': { TR: 'Sahne kataloğu açılamadı', EN: 'Scene catalog could not be opened' },
  'templates.retry': { TR: 'Tekrar dene', EN: 'Try again' },
  'templates.empty': { TR: 'Henüz hazır sahne yok', EN: 'No ready scenes yet' },
  'templates.empty_hint': { TR: 'Kendi videonu yükleyerek dublaj akışına devam edebilirsin.', EN: 'Upload your own video to continue the dubbing flow.' },
  'templates.all': { TR: 'Tümü', EN: 'All' },
  'templates.search': { TR: 'Sahne ara...', EN: 'Search scenes...' },
  'templates.popular': { TR: 'Popüler', EN: 'Popular' },
  'templates.shortest': { TR: 'En Kısa', EN: 'Shortest' },
  'templates.no_results': { TR: 'Bu kategoride sahne bulunamadı.', EN: 'No scenes were found in this category.' },
  'templates.demo': { TR: 'Demo', EN: 'Demo' },
  'templates.selected': { TR: 'Seçili', EN: 'Selected' },
  'templates.details': { TR: 'Detayları gör', EN: 'View details' },
  'templates.easy': { TR: 'Kolay', EN: 'Easy' },
  'templates.medium': { TR: 'Orta', EN: 'Medium' },
  'timeline.default_line': { TR: '{number}. repliğini buraya yaz.', EN: 'Write line {number} here.' },
  'timeline.duration_error': { TR: 'Replik bitiş zamanı video süresini aşıyor. Lütfen son repliği video bitişinden önce tamamlayın.', EN: 'A line ends after the video. Make sure the final line ends before the video does.' },
  'timeline.locked': { TR: 'Video işlenirken düzenleme geçici olarak kilitlenir.', EN: 'Editing is temporarily locked while the video is processed.' },
  'timeline.stop_active': { TR: 'Devam etmek için aktif kaydı durdurun.', EN: 'Stop the active recording to continue.' },
  'timeline.fix_lines': { TR: '{count} repliğin metnini veya zaman aralığını düzeltin.', EN: 'Fix the text or time range for {count} line(s).' },
  'timeline.record_more': { TR: 'Export için {count} repliği daha kaydedin.', EN: 'Record {count} more line(s) before exporting.' },
  'timeline.unsupported': { TR: 'Tarayıcınız mikrofon kaydını desteklemiyor. Güncel Chrome, Edge veya Safari kullanın.', EN: 'Your browser does not support microphone recording. Use a current version of Chrome, Edge, or Safari.' },
  'timeline.check_line': { TR: 'Replik metnini ve zaman aralığını kontrol edin.', EN: 'Check the line text and time range.' },
  'timeline.permission_denied': { TR: 'Mikrofon izni reddedildi. Adres çubuğundaki kilit simgesinden mikrofon iznini açıp tekrar deneyin.', EN: 'Microphone permission was denied. Allow microphone access from the lock icon in the address bar and try again.' },
  'timeline.no_microphone': { TR: 'Kullanılabilir mikrofon bulunamadı. Mikrofon bağlantısını ve Windows ses ayarlarını kontrol edin.', EN: 'No microphone was found. Check the microphone connection and your system sound settings.' },
  'timeline.microphone_busy': { TR: 'Mikrofon başka bir uygulama tarafından kullanılıyor. Diğer uygulamayı kapatıp tekrar deneyin.', EN: 'The microphone is being used by another application. Close it and try again.' },
  'timeline.microphone_error': { TR: 'Mikrofon açılamadı. Tarayıcı iznini ve ses aygıtını kontrol edip tekrar deneyin.', EN: 'The microphone could not be opened. Check browser permissions and the audio device, then try again.' },
  'timeline.max_lines': { TR: 'En fazla 20 replik ekleyebilirsiniz.', EN: 'You can add up to 20 lines.' },
  'timeline.new_line': { TR: 'Yeni replik', EN: 'New line' },
  'timeline.check_all': { TR: 'Tüm replik metinlerini ve zaman aralıklarını kontrol edin.', EN: 'Check all line texts and time ranges.' },
  'timeline.record_all': { TR: 'Videoyu oluşturmadan önce her repliği kaydedin.', EN: 'Record every line before creating the video.' },
  'timeline.title': { TR: 'Replik zaman çizelgesi', EN: 'Line timeline' },
  'timeline.subtitle': { TR: 'Her repliği kendi zaman aralığında seslendir.', EN: 'Record each line within its time range.' },
  'timeline.add': { TR: 'Replik ekle', EN: 'Add line' },
  'timeline.progress': { TR: 'Kayıt ilerlemesi', EN: 'Recording progress' },
  'timeline.completed': { TR: '{done}/{total} tamamlandı', EN: '{done}/{total} completed' },
  'timeline.demo_title': { TR: 'Demo medya yakında.', EN: 'Demo media coming soon.' },
  'timeline.demo_hint': { TR: 'Hazır replikleri düzenleyip kayıt akışını deneyebilirsin. Video önizleme ve MP4 export için kendi videonu yükle.', EN: 'Edit the prepared lines and try the recording flow. Upload your own video for video preview and MP4 export.' },
  'timeline.recording': { TR: 'Kayıt devam ediyor', EN: 'Recording in progress' },
  'timeline.recorded': { TR: 'Kayıt tamamlandı', EN: 'Recording complete' },
  'timeline.waiting': { TR: 'Kayıt bekliyor', EN: 'Waiting for recording' },
  'timeline.preview': { TR: 'Sahneyi oynat', EN: 'Play scene' },
  'timeline.delete': { TR: 'Repliği sil', EN: 'Delete line' },
  'timeline.text_aria': { TR: 'Replik {number} metni', EN: 'Line {number} text' },
  'timeline.start': { TR: 'Başlangıç', EN: 'Start' },
  'timeline.end': { TR: 'Bitiş', EN: 'End' },
  'timeline.invalid': { TR: 'Metin boş olmamalı; bitiş, başlangıçtan sonra ve video süresi içinde olmalı.', EN: 'Text cannot be empty; the end must be after the start and within the video duration.' },
  'timeline.stop': { TR: 'Kaydı durdur', EN: 'Stop recording' },
  'timeline.rerecord': { TR: 'Yeniden kaydet', EN: 'Record again' },
  'timeline.start_recording': { TR: 'Kaydı başlat', EN: 'Start recording' },
  'timeline.auto_stop': { TR: 'Süre bitince otomatik durur', EN: 'Stops automatically when time runs out' },
  'timeline.mute': { TR: 'Orijinal sesi tamamen kapat', EN: 'Mute original audio completely' },
  'timeline.subtitles': { TR: 'Altyazıları videoya göm', EN: 'Burn subtitles into the video' },
  'timeline.create': { TR: 'Kendi Sesimle Videoyu Oluştur', EN: 'Create Video with My Voice' },
  'timeline.ready': { TR: 'Tüm replikler hazır; videonu oluşturabilirsin.', EN: 'All lines are ready; you can create your video.' },
  'demo_scenes.title': { TR: 'Örnek Sahneler (Demo)', EN: 'Sample Scenes (Demo)' },
  'demo_scenes.cta': { TR: 'Hemen Dublajla', EN: 'Dub This Scene' },
  'ethics.title': { TR: 'Etik ve telif bilinci', EN: 'Ethics and copyright awareness' },
  'ethics.description': { TR: 'Bu uygulama eğlence, parodi ve portföy amaçlıdır. Gerçek kişileri taklit etmek, yanıltıcı içerik üretmek veya telifli içerikleri izinsiz dağıtmak kullanıcının sorumluluğundadır. Mikrofon kayıtları yalnızca video işlenirken kullanılır ve işlem sonrası geçici sunucu kopyaları silinir.', EN: 'This application is intended for entertainment, parody, and portfolio use. Users are responsible for avoiding impersonation, misleading content, and unauthorized distribution of copyrighted material. Microphone recordings are used only while processing the video, and temporary server copies are deleted afterward.' },
  'voice.title': { TR: 'Ses stili', EN: 'Voice style' },
  'voice.announcer': { TR: 'Spiker', EN: 'Announcer' },
  'voice.announcer_desc': { TR: 'Net ve güvenli', EN: 'Clear and confident' },
  'voice.robot': { TR: 'Robot', EN: 'Robot' },
  'voice.robot_desc': { TR: 'Mekanik ve ağır', EN: 'Mechanical and deep' },
  'voice.dramatic': { TR: 'Dramatik', EN: 'Dramatic' },
  'voice.dramatic_desc': { TR: 'Vurgulu anlatım', EN: 'Expressive delivery' },
  'voice.documentary': { TR: 'Belgesel', EN: 'Documentary' },
  'voice.documentary_desc': { TR: 'Sakin ve meraklı', EN: 'Calm and curious' },
  'voice.energetic': { TR: 'Enerjik', EN: 'Energetic' },
  'voice.energetic_desc': { TR: 'Hızlı ve canlı', EN: 'Fast and lively' },
  'job.failed': { TR: 'Video oluşturulamadı', EN: 'Video could not be created' },
  'dubs.title': { TR: 'Dublajlar', EN: 'Dubs' },
  'dubs.description': { TR: 'Topluluğun kaydettiği efsane dublajları keşfet.', EN: 'Discover memorable dubs recorded by the community.' },
  'dubs.demo_notice': { TR: 'Henüz gerçek dublaj yok. Aşağıdaki içerikler Demo amaçlı listelenmektedir.', EN: 'There are no public dubs yet. The content below is listed for demo purposes.' },
  'dubs.like_login': { TR: 'Beğenmek için giriş yapmalısınız.', EN: 'You need to log in to like a dub.' },
  'dubs.action_failed': { TR: 'İşlem başarısız.', EN: 'The action failed.' },
  'dubs.preparing': { TR: 'Video hazırlanıyor...', EN: 'Preparing video...' },
  'dubs.report': { TR: 'İçeriği Raporla', EN: 'Report content' },
  'dubs.views': { TR: 'İzlenme Sayısı', EN: 'View count' },
  'dubs.unlike': { TR: 'Beğeniyi Geri Al', EN: 'Remove like' },
  'dubs.like': { TR: 'Beğen', EN: 'Like' },
  'dubs.comments': { TR: 'Yorumlar', EN: 'Comments' },
  'dubs.download': { TR: 'İndir', EN: 'Download' },
  'dubs.comedy': { TR: 'Komedi', EN: 'Comedy' },
  'dubs.empty_title': { TR: 'İlk dublajı sen paylaş', EN: 'Share the first dub' },
  'dubs.empty_desc': { TR: 'Topluluk akışında henüz yayınlanmış bir video yok. Kendi videonu seslendirip görünürlüğünü herkese açık yapabilirsin.', EN: 'There are no published videos in the community feed yet. Dub your own video and make it public when it is ready.' },
  'dubs.empty_cta': { TR: 'Dublaj oluşturmaya başla', EN: 'Create a dub' },
  'dubs.load_error_title': { TR: 'Dublajlar yüklenemedi', EN: 'Dubs could not be loaded' },
  'dubs.load_error_desc': { TR: 'Sunucuya şu anda ulaşılamıyor. Biraz sonra tekrar deneyebilir veya stüdyoda çalışmaya devam edebilirsin.', EN: 'The server is currently unavailable. Try again shortly or continue working in the studio.' },
  'comments.load_error': { TR: 'Yorumlar yüklenirken hata oluştu.', EN: 'Comments could not be loaded.' },
  'comments.added': { TR: 'Yorumunuz eklendi.', EN: 'Your comment was added.' },
  'comments.add_error': { TR: 'Yorum eklenemedi (1-500 karakter olmalı).', EN: 'Comment could not be added (must be 1-500 characters).' },
  'comments.delete_confirm': { TR: 'Yorumunuzu silmek istiyor musunuz?', EN: 'Do you want to delete your comment?' },
  'comments.deleted': { TR: 'Yorum silindi.', EN: 'Comment deleted.' },
  'comments.delete_error': { TR: 'Yorum silinemedi.', EN: 'Comment could not be deleted.' },
  'comments.loading': { TR: 'Yükleniyor...', EN: 'Loading...' },
  'comments.empty': { TR: 'İlk yorumu sen yaz!', EN: 'Write the first comment!' },
  'comments.delete': { TR: 'Sil', EN: 'Delete' },
  'comments.placeholder': { TR: 'Yorumunuz (En fazla 500 karakter)', EN: 'Your comment (up to 500 characters)' },
  'comments.send': { TR: 'Gönder', EN: 'Send' },
  'comments.login_prefix': { TR: 'Yorum yazmak için', EN: 'To write a comment,' },
  'comments.login': { TR: 'giriş yapın', EN: 'log in' },
  'membership.hero': { TR: 'Daha yüksek kalite, daha fazla yaratıcı araç.', EN: 'Higher quality, more creative tools.' },
  'membership.hero_desc': { TR: 'Ücretsiz planda kendi sesinle dublaj yapmaya devam et. VIP ile 1080p export ve opsiyonel AI ses modunu aç.', EN: 'Keep dubbing with your own voice on the Free plan. Unlock 1080p export and optional AI voice with VIP.' },
  'membership.free': { TR: 'Ücretsiz', EN: 'Free' },
  'membership.free_title': { TR: 'Başlamak için yeterli', EN: 'Everything you need to start' },
  'membership.free_desc': { TR: 'Video yükle, repliklerini mikrofonla kaydet, altyazılı MP4 çıktını al.', EN: 'Upload a video, record your lines, and export a subtitled MP4.' },
  'membership.current': { TR: 'Mevcut planın', EN: 'Your current plan' },
  'membership.days': { TR: '30 günlük erişim', EN: '30-day access' },
  'membership.vip_desc': { TR: '1080p çıktı ve AI ses araçları backend tarafından hesabına özel açılır.', EN: '1080p export and AI voice tools are securely enabled for your account by the backend.' },
  'membership.period': { TR: '/ 30 gün', EN: '/ 30 days' },
  'membership.ai_mode': { TR: 'AI sesle dublaj modu', EN: 'AI voice dubbing mode' },
  'membership.badge': { TR: 'Profil ve menüde VIP rozeti', EN: 'VIP badge in your profile and menu' },
  'membership.active': { TR: 'VIP üyeliğin aktif', EN: 'Your VIP membership is active' },
  'membership.buy': { TR: 'VIP üyelik al', EN: 'Get VIP membership' },
  'membership.feature': { TR: 'Özellik', EN: 'Feature' },
  'membership.included': { TR: 'Dahil', EN: 'Included' },
  'membership.locked': { TR: 'Kilitli', EN: 'Locked' },
  'membership.feature.mic': { TR: 'Kendi mikrofonunla dublaj', EN: 'Dub with your microphone' },
  'membership.feature.upload': { TR: 'Hazır sahne ve video yükleme', EN: 'Ready scenes and video uploads' },
  'membership.feature.quality': { TR: 'MP4 export kalitesi', EN: 'MP4 export quality' },
  'membership.feature.ai': { TR: 'AI sesle dublaj', EN: 'AI voice dubbing' },
  'membership.feature.badge': { TR: 'Hesapta VIP rozeti', EN: 'VIP account badge' },
  'membership.secure': { TR: 'Güvenli yetkilendirme', EN: 'Secure authorization' },
  'membership.secure_desc': { TR: 'VIP kontrolü yalnız arayüzde değil backend’de yapılır. Ücretsiz bir hesap kilitli API’yi doğrudan çağıramaz.', EN: 'VIP access is enforced by the backend, not only by the interface. A Free account cannot call locked APIs directly.' },
  'membership.payment': { TR: 'Ödeme doğrulaması', EN: 'Payment verification' },
  'membership.payment_desc': { TR: 'Shopier ödemesi doğrulandıktan sonra hesabına süreli VIP erişimi tanımlanır. Kart bilgileri DublajLab’da tutulmaz.', EN: 'Time-limited VIP access is added after Shopier payment verification. DublajLab does not store card details.' },
  'membership.paid': { TR: 'Ödemeyi tamamladın mı?', EN: 'Completed your payment?' },
  'membership.refresh_desc': { TR: 'Doğrulama sonrasında üyelik durumunu yenileyebilirsin.', EN: 'Refresh your membership status after verification.' },
  'membership.refresh': { TR: 'Üyeliği yenile', EN: 'Refresh membership' },
  'membership.login_first': { TR: 'VIP üyelik almak için önce giriş yapın.', EN: 'Log in before purchasing VIP membership.' },
  'membership.payment_unavailable': { TR: 'Ödeme altyapısı yakında açılacak veya şu an kapalı.', EN: 'Payment infrastructure is not available yet or is currently disabled.' },
  'membership.payment_error': { TR: 'Ödeme başlatılamadı. Lütfen tekrar deneyin.', EN: 'Payment could not be started. Please try again.' },
  'membership.connection_error': { TR: 'Bağlantı hatası oluştu.', EN: 'A connection error occurred.' },
  'membership.vip_refreshed': { TR: 'VIP üyeliğiniz aktif. Özellikler açıldı.', EN: 'Your VIP membership is active. Features are unlocked.' },
  'membership.pending': { TR: 'Ödeme doğrulaması henüz tamamlanmamış görünüyor.', EN: 'Payment verification does not appear to be complete yet.' },
  'membership.refresh_error': { TR: 'Üyelik durumu yenilenemedi.', EN: 'Membership status could not be refreshed.' },
  'membership.order_created': { TR: 'Sipariş kaydınız oluşturuldu: {id}. (Ödeme altyapısı henüz yapılandırılmadı)', EN: 'Your order was created: {id}. (Payment infrastructure is not configured yet)' },
  'error.daily_title': { TR: 'Günlük demo limiti doldu', EN: 'Daily demo limit reached' },
  'error.daily_hint': { TR: 'Public demo kotası UTC gün başlangıcında yenilenir. Daha sonra tekrar deneyin.', EN: 'The public demo quota resets at the start of each UTC day. Try again later.' },
  'error.limit_title': { TR: 'Public demo limiti aşıldı', EN: 'Public demo limit exceeded' },
  'error.limit_hint': { TR: 'Daha küçük veya daha kısa bir video/kayıt seçip yeniden deneyin.', EN: 'Choose a smaller or shorter video/recording and try again.' },
  'error.backend_title': { TR: 'Backend bağlantısı kurulamadı', EN: 'Could not connect to the backend' },
  'error.backend_hint': { TR: 'Backend sunucusunun çalıştığını ve API adresinin doğru ayarlandığını kontrol edin.', EN: 'Check that the backend is running and the API address is configured correctly.' },
  'error.ffmpeg_title': { TR: 'Medya motoru hazır değil', EN: 'Media engine is not ready' },
  'error.ffmpeg_hint': { TR: 'FFmpeg kurulumunu ve PATH ayarını kontrol edin; ardından backend sunucusunu yeniden başlatın.', EN: 'Check the FFmpeg installation and PATH, then restart the backend server.' },
  'error.microphone_title': { TR: 'Mikrofon erişimi gerekli', EN: 'Microphone access is required' },
  'error.microphone_hint': { TR: 'Adres çubuğundaki kilit simgesinden mikrofon iznini açın ve kayıt düğmesine yeniden basın.', EN: 'Allow microphone access from the lock icon in the address bar, then press record again.' },
  'error.generic_title': { TR: 'İşlem tamamlanamadı', EN: 'The operation could not be completed' },
  'error.generic_hint': { TR: 'Bilgileri kontrol edip tekrar deneyin. Sorun sürerse sunucu hata kayıtlarını kontrol edin.', EN: 'Check the information and try again. If the issue continues, check the server error logs.' },
  'error.server_message': { TR: 'İstek tamamlanamadı. Bilgileri kontrol edip tekrar deneyin.', EN: 'The request could not be completed. Check your input and try again.' },
  'error.backend_message': { TR: 'Sunucuya ulaşılamadı.', EN: 'The server could not be reached.' },
  'error.ffmpeg_message': { TR: 'Medya işlemi tamamlanamadı.', EN: 'Media processing could not be completed.' },
  'error.limit_message': { TR: 'Public demo sınırı aşıldı.', EN: 'A public demo limit was exceeded.' },
  'error.vip_message': { TR: 'Bu özellik yalnızca VIP kullanıcılara açıktır.', EN: 'This feature is available to VIP users only.' },
  'error.lipsync_message': { TR: 'Dudak senkronizasyonu şu anda kullanılamıyor.', EN: 'Lip sync is currently unavailable.' },
  'action.upload_error': { TR: 'Video yüklenirken bir hata oluştu.', EN: 'An error occurred while uploading the video.' },
  'action.retry_upload': { TR: 'Yüklemeyi tekrar dene', EN: 'Retry upload' },
  'action.retry_export': { TR: 'Export’u tekrar dene', EN: 'Retry export' },
  'action.template_file_error': { TR: 'Template video dosyası yüklenemedi. Dosya yolunu ve lisans metadata’sını kontrol edin.', EN: 'The template video could not be loaded. Check the file path and license metadata.' },
  'action.template_error': { TR: 'Hazır sahne açılamadı.', EN: 'The ready scene could not be opened.' },
  'action.export_preparing': { TR: 'Export isteği hazırlanıyor.', EN: 'Preparing export request.' },
  'action.export_ready': { TR: 'Dublaj videosu hazır.', EN: 'The dubbed video is ready.' },
  'action.saved': { TR: 'Dublajın hesabına kaydedildi.', EN: 'Your dub was saved to your account.' },
  'action.processing_error': { TR: 'Video işlenirken bir hata oluştu.', EN: 'An error occurred while processing the video.' },
  'action.no_output': { TR: 'Job tamamlandı ancak çıktı bağlantısı alınamadı.', EN: 'The job completed, but no output link was returned.' },
  'action.ai_vip': { TR: 'AI sesle dublaj VIP üyelere özeldir.', EN: 'AI voice dubbing is available to VIP members only.' },
  'action.upload_first': { TR: 'Önce bir video yükleyin.', EN: 'Upload a video first.' },
  'action.script_required': { TR: 'Dublaj metni boş bırakılamaz.', EN: 'The dubbing script cannot be empty.' },
  'action.template_export_unavailable': { TR: 'MP4 export için template video dosyasının projeye güvenli biçimde eklenmesi veya kendi videonun yüklenmesi gerekir.', EN: 'To export MP4, add the template video safely to the project or upload your own video.' },
  'action.tiktok_hint': { TR: 'Videonuzu indirip TikTok uygulamasından yükleyebilirsiniz.', EN: 'Download your video, then upload it from the TikTok app.' },
  'action.reels_hint': { TR: 'Videonuzu indirip Reels olarak paylaşabilirsiniz.', EN: 'Download your video, then share it as a Reel.' },
  'howto.title': { TR: 'Nasıl Oynanır?', EN: 'How Does It Work?' },
  'howto.description': { TR: "DublajLab'de kendi sesinle eğlenceli videolar üretmek çok kolay.", EN: 'Creating fun videos with your own voice is easy in DublajLab.' },
  'howto.step1': { TR: 'Sahne Seç', EN: 'Choose a Scene' },
  'howto.step1_desc': { TR: 'Sahneler galerisinden bir video seç veya kendi cihazından video yükle.', EN: 'Choose a video from the scene gallery or upload one from your device.' },
  'howto.step2': { TR: 'Repliği Oku', EN: 'Read the Line' },
  'howto.step2_desc': { TR: 'Zaman çizelgesindeki replikleri takip et, sıran geldiğinde mikrofonla sesini kaydet.', EN: 'Follow the lines on the timeline and record your voice when it is your turn.' },
  'howto.step3': { TR: 'Videoyu İndir', EN: 'Download the Video' },
  'howto.step3_desc': { TR: 'Tüm replikleri kaydettikten sonra sistem otomatik olarak sesi miksler ve MP4 olarak sana sunar.', EN: 'After you record every line, the system mixes the audio and creates an MP4 for you.' },
  'howto.start': { TR: 'Hemen Başla', EN: 'Get Started' },
  'daily.title': { TR: 'Günün Dublajı', EN: 'Daily Dub' },
  'daily.description': { TR: 'Bugün en çok güldüren performans.', EN: "Today's funniest performance." },
  'daily.demo': { TR: 'Demo İçerik', EN: 'Demo Content' },
  'daily.winner': { TR: 'Günün Kazananı', EN: "Today's Winner" },
  'daily.demo_title': { TR: 'Toplantı faciası (Demo)', EN: 'Meeting disaster (Demo)' },
  'daily.voice_by': { TR: 'Seslendiren', EN: 'Voiced by' },
  'daily.quote': { TR: '“Tüm gün süren o toplantı beş dakika sürecek dediler... Sonra herkes kahve molasına çıktı ama mikrofonum açık kalmış!”', EN: '“They said that all-day meeting would take five minutes... Then everyone went for coffee, but my microphone was still on!”' },
  'daily.watch': { TR: 'Dublajı İzle', EN: 'Watch the Dub' },
  'daily.create': { TR: 'Sen de Seslendir', EN: 'Record Your Version' },
  'daily.all': { TR: 'Tüm Dublajlar', EN: 'All Dubs' },
  'daily.notice': { TR: '* Yakında gerçek topluluk içerikleri eklenecektir. Bu sayfa tasarım demosudur.', EN: '* Real community content will be added soon. This page is a design demo.' },

  // Promo & Favorites
  'promo.vip_version': { TR: 'VIP Sürüm', EN: 'VIP Version' },
  'promo.title': { TR: 'Daha yüksek kalite export seçeneği.', EN: 'Higher quality export option.' },
  'promo.desc': { TR: 'Ücretsiz üyelikte 720p MP4 export; VIP üyelikte 1080p ve AI ses modu sunulur.', EN: 'Free membership includes 720p MP4 export; VIP adds 1080p and AI voice mode.' },
  'promo.toast': { TR: 'VIP üyelik sistemi henüz aktif değil. (Demo)', EN: 'VIP membership system is not active yet. (Demo)' },
  'promo.cta': { TR: 'VIP özelliklerini keşfet', EN: 'Discover VIP features' },
  'promo.vip_desc': { TR: 'VIP üyelik ile 1080p çıktı ve AI sesle dublaj modunu açarsın.', EN: 'Unlock 1080p export and AI voice dubbing mode with VIP membership.' },
  'favorites.title': { TR: 'Favorilerim', EN: 'My Favorites' },
  'favorites.desc': { TR: 'Sonra oynamak için işaretlediğin sahneler.', EN: 'Scenes you marked to play later.' },
  'favorites.empty_title': { TR: 'Henüz favorin yok.', EN: 'No favorites yet.' },
  'favorites.empty_desc': { TR: 'Beğendiğin sahneyi kapağındaki kalple işaretle, burada birikir.', EN: 'Mark a scene you like with a heart, it will appear here.' },
  'favorites.discover': { TR: 'Sahne Keşfet', EN: 'Discover Scenes' },
  'vip.button_short': { TR: 'VIP Ol', EN: 'Go VIP' },

  // UserLibrary
  'library.fetch_error': { TR: 'Projeler yüklenirken hata oluştu.', EN: 'An error occurred while loading projects.' },
  'library.delete_confirm': { TR: 'Bu projeyi silmek istediğinize emin misiniz?', EN: 'Are you sure you want to delete this project?' },
  'library.delete_error': { TR: 'Silme işlemi başarısız.', EN: 'Deletion failed.' },
  'library.made_public': { TR: 'Proje herkese açık yapıldı.', EN: 'Project is now public.' },
  'library.made_private': { TR: 'Proje gizlendi.', EN: 'Project is now private.' },
  'library.update_error': { TR: 'Güncelleme başarısız.', EN: 'Update failed.' },
  'library.title': { TR: 'Kataloğum', EN: 'My Library' },
  'library.deleted': { TR: 'Proje silindi.', EN: 'Project deleted.' },
  'library.delete': { TR: 'Projeyi sil', EN: 'Delete project' },
  'library.empty_subtitle': { TR: 'Yer aldığın 0 dublaj. İzle, indir ya da stüdyoda yeniden miksle.', EN: '0 dubs you participated in. Watch, download or remix in the studio.' },
  'library.empty_title': { TR: 'Henüz dublajın yok', EN: 'You have no dubs yet' },
  'library.empty_desc': { TR: 'Kendi videonu yükle ve ilk dublajını oluştur; tamamlanan çıktı burada görünsün.', EN: 'Upload your own video and create your first dub; the completed result will appear here.' },
  'library.subtitle': { TR: 'Yer aldığın {count} dublaj. İzle, indir ya da stüdyoda yeniden miksle.', EN: '{count} dubs you participated in. Watch, download or remix in the studio.' },
  'library.public_tooltip': { TR: 'Şu an herkese açık. Gizlemek için tıkla.', EN: 'Currently public. Click to make it private.' },
  'library.private_tooltip': { TR: 'Herkese açık yaptığında Dublajlar sayfasında görünür.', EN: 'When you make it public, it will appear on the Dubs page.' },
  'library.public': { TR: 'Açık', EN: 'Public' },
  'library.private': { TR: 'Gizli', EN: 'Private' },
  'library.expired_tooltip': { TR: 'Dosya sunucudan silinmiş (Süre aşımı)', EN: 'File deleted from server (Expired)' },
  'library.expired': { TR: 'Süresi Dolmuş', EN: 'Expired' },

  // UserScenes
  'scenes.feat1_title': { TR: 'Video', EN: 'Video' },
  'scenes.feat1_desc': { TR: 'MP4 yükle, süre ve ses otomatik ölçülür.', EN: 'Upload MP4, duration and audio are measured automatically.' },
  'scenes.feat2_title': { TR: 'Karakterler', EN: 'Characters' },
  'scenes.feat2_desc': { TR: 'Sahnede konuşan her kişiyi ekle.', EN: 'Add every person who speaks in the scene.' },
  'scenes.feat3_title': { TR: 'Replikler', EN: 'Lines' },
  'scenes.feat3_desc': { TR: 'Kimin ne zaman konuştuğunu işaretle.', EN: 'Mark who speaks and when.' },
  'scenes.feat4_title': { TR: 'Arka plan sesi', EN: 'Background audio' },
  'scenes.feat4_desc': { TR: 'Vokal ayırıcıyla ayır ya da hazır dosyanı yükle.', EN: 'Separate with a vocal remover or upload a ready file.' },
  'scenes.feat5_title': { TR: 'Yayınla', EN: 'Publish' },
  'scenes.feat5_desc': { TR: 'Kendi odanda oyna ya da herkese açılması için gönder.', EN: 'Play in your own room or send for public release.' },
  'scenes.studio': { TR: 'Stüdyo', EN: 'Studio' },
  'scenes.desc': { TR: 'Kendi sahneni kur, repliklerini ayarla, arka plan sesini hazırla ve incelemeye gönder. Onaylanan sahneler yayına girer ve adın "Ekleyen" olarak görünür.', EN: 'Set up your own scene, adjust your lines, prepare the background audio and send for review. Approved scenes go live with your name as the Contributor.' },
  'scenes.status_draft': { TR: 'Açık Taslak', EN: 'Open Draft' },
  'scenes.status_review': { TR: 'İncelenmede', EN: 'In Review' },
  'scenes.status_published': { TR: 'Yayında', EN: 'Published' },
  'scenes.copyright_prefix': { TR: 'Gönderdiğin içeriğin haklarına sahip olmalısın. Ayrıntılar: ', EN: 'You must own the rights to the content you submit. Details: ' },
  'scenes.copyright_link': { TR: 'Telif bildirimi', EN: 'Copyright notice' },
  'scenes.empty_title': { TR: 'Henüz sahne göndermedin', EN: 'You haven\'t submitted a scene yet' },
  'scenes.empty_desc': { TR: 'Bir film ya da dizi sahnesinin videosunu yükle, kimin ne zaman konuştuğunu işaretle, arka plan sesini hazırla ve incelemeye gönder.', EN: 'Upload a video of a movie or series scene, mark who speaks when, prepare the background audio, and send it for review.' },
  'scenes.create_first': { TR: 'İlk Sahneni Oluştur', EN: 'Create Your First Scene' },

  // PublicProfile
  'profile.level_desc': { TR: 'Acemi Dublajcı · Seviye 1', EN: 'Novice Dubber · Level 1' },
  'profile.joined': { TR: 'Eylül 2026 Katıldı', EN: 'Joined Sep 2026' },
  'profile.edit': { TR: 'Profili Düzenle', EN: 'Edit Profile' },
  'profile.voice_level': { TR: 'Seslendirme — seviye 3', EN: 'Voice acting — level 3' },
  'profile.dubs': { TR: 'Dublaj', EN: 'Dubs' },
  'profile.games': { TR: 'Oyun', EN: 'Games' },
  'profile.lines': { TR: 'Replik', EN: 'Lines' },
  'profile.reactions': { TR: 'Tepki', EN: 'Reactions' },
  'profile.friends': { TR: 'Arkadaş', EN: 'Friends' },
  'profile.recent_dubs': { TR: 'Son dublajlar', EN: 'Recent dubs' },
  'profile.no_dubs': { TR: 'Henüz dublaj yok.', EN: 'No dubs yet.' },
  'profile.start_game': { TR: 'Bir oyun başlat', EN: 'Start a game' },

  // UserCredits
  'credits.title': { TR: 'Kredilerim', EN: 'My Credits' },
  'credits.desc': { TR: 'Ücretsiz sürümde oyunlar kredi ile oynanır, her sahne için ücret düşülür. VIP ve VIP+ üyeler sınırsız oynar.', EN: 'In the free version, games are played with credits. Each scene consumes credits. VIP members play unlimited.' },
  'credits.available': { TR: 'Kullanılabilir', EN: 'Available' },

  'credits.free': { TR: 'Ücretsiz', EN: 'Free' },
  'credits.permanent': { TR: 'Kalıcı', EN: 'Permanent' },
  'credits.in_game': { TR: 'Oyunda Tutulan', EN: 'Held in Game' },
  'credits.next_refresh': { TR: 'Sonraki Yenilenme', EN: 'Next Refresh' },
  'credits.cost_per_scene': { TR: 'Her sahne: 10 kredi / oyuncu', EN: 'Each scene: 10 credits / player' },
  'credits.daily_info': { TR: 'Ücretsiz kredin her gün 35 krediye tamamlanır. Bu yaklaşık 3 sahne eder.', EN: 'Your free credits top up to 35 every day. This is about 3 scenes.' },
  'credits.perm_info': { TR: 'Kalıcı krediler günlük yenilemede silinmez; önce ücretsiz krediler harcanır.', EN: 'Permanent credits are not wiped daily; free credits are used first.' },
  'credits.transactions': { TR: 'Hareketler', EN: 'Transactions' },
  'credits.filter_all': { TR: 'Tümü', EN: 'All' },
  'credits.filter_earned': { TR: 'Kazanılan', EN: 'Earned' },
  'credits.filter_spent': { TR: 'Harcanan', EN: 'Spent' },
  'credits.admin_info': { TR: 'Yönetici işlemleri kendi adıyla görünür, gerekçe varsa altında yazar.', EN: 'Admin actions appear with their names, reasons are written below if any.' },
  'credits.welcome': { TR: 'Hoş geldin kredisi', EN: 'Welcome credit' },
  'credits.balance_35': { TR: 'Bakiye 35', EN: 'Balance 35' },
  'credits.no_tx': { TR: 'Bu kategoriye ait işlem bulunamadı.', EN: 'No transactions found in this category.' },

  // AccountSettings
  'account.save_profile': { TR: 'Profil kaydı', EN: 'Profile save' },
  'account.saved_success': { TR: 'Profil değişiklikleri kaydedildi.', EN: 'Profile changes were saved.' },
  'account.saving': { TR: 'Kaydediliyor...', EN: 'Saving...' },
  'account.coming_soon': { TR: 'Bu ayar yakında kullanıma açılacak.', EN: 'This setting will be available soon.' },
  'account.err_username_mismatch': { TR: 'Kullanıcı adı eşleşmiyor.', EN: 'Username does not match.' },
  'account.err_password_req': { TR: 'Lütfen şifrenizi girin.', EN: 'Please enter your password.' },
  'account.deleted_success': { TR: 'Hesabınız kalıcı olarak silindi.', EN: 'Your account has been permanently deleted.' },
  'account.err_generic': { TR: 'Bir hata oluştu', EN: 'An error occurred' },
  'account.badge_novice': { TR: 'Acemi Denek', EN: 'Novice Subject' },
  'account.level_1': { TR: 'Seviye 1', EN: 'Level 1' },
  'account.status_title': { TR: 'Deney Statüsü', EN: 'Experiment Status' },
  'account.vip_access': { TR: 'VIP Erişim', EN: 'VIP Access' },
  'account.free_access': { TR: 'Ücretsiz Erişim', EN: 'Free Access' },
  'account.vip_desc': { TR: '1080p export ve AI sesle dublaj özelliklerin aktif.', EN: '1080p export and AI voice dubbing features are active.' },
  'account.free_desc': { TR: 'Kendi sesinle dublaj ve 720p MP4 export kullanabilirsin. VIP ile 1080p ve AI ses modunu açabilirsin.', EN: 'You can use dubbing with your own voice and 720p MP4 export. Unlock 1080p and AI voice mode with VIP.' },
  'account.vip_details': { TR: 'VIP Detayları', EN: 'VIP Details' },
  'account.go_vip': { TR: 'VIP Ol', EN: 'Go VIP' },
  'account.credits': { TR: 'Krediler', EN: 'Credits' },
  'account.edit_title': { TR: 'Profilini Düzenle', EN: 'Edit Profile' },
  'account.edit_desc': { TR: 'Bu bilgiler herkese açık profilinde görünür.', EN: 'This information appears on your public profile.' },
  'account.username': { TR: 'Kullanıcı Adı', EN: 'Username' },
  'account.username_hint': { TR: 'Sadece harf ve rakam kullanabilirsin. Ayda bir kez değiştirilebilir.', EN: 'You can only use letters and numbers. Can be changed once a month.' },
  'account.bio': { TR: 'Biyografi (Hakkında)', EN: 'Biography (About)' },
  'account.bio_placeholder': { TR: 'Kendinden kısaca bahset. Hangi tür sahneleri seversin?', EN: 'Tell us briefly about yourself. What kind of scenes do you like?' },
  'account.avatar': { TR: 'Avatar Adresi (URL)', EN: 'Avatar Address (URL)' },
  'account.avatar_hint': { TR: 'Şimdilik yalnızca adres kabul ediliyor (Discord ya da başka bir yerdeki resminin bağlantısı). Dosya yükleme henüz yok.', EN: 'Only addresses are accepted for now (link to your picture on Discord or elsewhere). No file upload yet.' },
  'account.save_changes': { TR: 'Değişiklikleri Kaydet', EN: 'Save Changes' },
  'account.security_title': { TR: 'Hesap Güvenliği', EN: 'Account Security' },
  'account.email_unverified': { TR: 'E-posta adresin henüz doğrulanmadı.', EN: 'Your email address is not verified yet.' },
  'account.pw_reset_prefix': { TR: 'Şifreni değiştirmek için e-postana bir sıfırlama bağlantısı iste: ', EN: 'Request a reset link to your email to change your password: ' },
  'account.contact_support': { TR: 'Destek ile iletişime geç', EN: 'Contact support' },
  'account.privacy_title': { TR: 'Gizlilik', EN: 'Privacy' },
  'account.privacy_desc': { TR: 'Profilini kimlerin görebileceğini ayarla. Gizli profiller toplulukta listelenmez.', EN: 'Set who can see your profile. Private profiles are not listed in the community.' },
  'account.hide_account': { TR: 'Hesabımı Gizle', EN: 'Hide My Account' },
  'account.only_you': { TR: 'Sadece sen görebilirsin', EN: 'Only you can see' },
  'account.discord_title': { TR: 'Discord Bağlantısı', EN: 'Discord Connection' },
  'account.discord_desc': { TR: 'Discord hesabını bağlayarak topluluk sunucumuzda lab rolünü kap ve seviyene göre özel rozetler kazan.', EN: 'Connect your Discord account to get the lab role on our community server and earn special badges based on your level.' },
  'account.connected': { TR: 'Bağlandı', EN: 'Connected' },
  'account.connect_discord': { TR: 'Discord Hesabını Bağla', EN: 'Connect Discord Account' },
  'account.delete_title': { TR: 'Hesabı kalıcı olarak sil', EN: 'Permanently delete account' },
  'account.delete_warning': { TR: 'Bu işlem geri alınamaz. Devam etmeden önce aşağıdakileri oku:', EN: 'This action cannot be undone. Read the following before continuing:' },
  'account.del_rule1': { TR: 'Kullanıcı adın ve e-postan serbest bırakılır, hesabına bir daha giriş yapamazsın.', EN: 'Your username and email will be released, you will not be able to log in to your account again.' },
  'account.del_rule2': { TR: 'Toplulukta paylaştığın dublajlar, oynadığın oyunların parçası olduğu için kalır.', EN: 'The dubs you shared in the community will remain as they are part of the games you played.' },
  'account.del_rule3': { TR: 'Ödeme ve kredi kayıtları muhasebe yükümlülüğü gereği saklanır.', EN: 'Payment and credit records are kept due to accounting obligations.' },
  'account.del_rule4': { TR: 'Silinen hesap geri getirilemez; istersen yeni bir hesap açabilirsin.', EN: 'A deleted account cannot be restored; you can open a new account if you want.' },
  'account.privacy_policy_notice': { TR: 'Verilerinin nasıl işlendiğini KVKK aydınlatma metninde okuyabilirsin.', EN: 'You can read how your data is processed in the GDPR clarification text.' },
  'account.want_to_delete': { TR: 'Hesabımı silmek istiyorum', EN: 'I want to delete my account' },
  'account.confirm_username': { TR: 'Onaylamak için kullanıcı adını yaz:', EN: 'Type your username to confirm:' },
  'account.password': { TR: 'Şifren', EN: 'Your password' },
  'account.verify_ownership': { TR: 'Hesabın gerçekten sana ait olduğunu doğruluyoruz.', EN: 'We are verifying that the account really belongs to you.' },
  'account.deleting': { TR: 'Siliniyor...', EN: 'Deleting...' },
  'account.delete_permanently': { TR: 'Hesabı kalıcı olarak sil', EN: 'Permanently delete account' },

  // Membership
  'membership.lab_vip': { TR: 'DublajLab VIP', EN: 'DublajLab VIP' },
  'membership.which_version': { TR: 'Hangi Sürüm Sana Göre?', EN: 'Which Version is for You?' },
  'membership.compare_desc': { TR: 'Ücretsiz public demo ile VIP deneyimi arasındaki farkı incele.', EN: 'Review the difference between the free public demo and the VIP experience.' },
  'membership.demo_title': { TR: 'Public Demo', EN: 'Public Demo' },
  'membership.current_plan': { TR: 'Şu Anki Plan', EN: 'Current Plan' },
  'membership.standard_quality': { TR: 'Standart Kalite', EN: 'Standard Quality' },
  'membership.demo_res': { TR: 'Sadece 480p çözünürlüğünde indirme.', EN: 'Only 480p resolution download.' },
  'membership.limited_export': { TR: 'Sınırlı Export', EN: 'Limited Export' },
  'membership.daily_5_export': { TR: 'Günlük sadece 5 export hakkı.', EN: 'Only 5 exports per day.' },
  'membership.temp_storage': { TR: 'Geçici Depolama', EN: 'Temporary Storage' },
  'membership.del_6_hours': { TR: 'Export alınan dosyalar 6 saat sonra silinir.', EN: 'Exported files are deleted after 6 hours.' },
  'membership.own_voice': { TR: 'Kendi Sesinle', EN: 'With Your Own Voice' },
  'membership.only_mic': { TR: 'Sadece kendi mikrofonunla dublaj yapabilirsin.', EN: 'You can only dub with your own microphone.' },
  'membership.slow_process': { TR: 'Yavaş İşlem', EN: 'Slow Process' },
  'membership.queue_wait': { TR: 'Kuyrukta beklersin, sunucu yoğunluğuna göre gecikmeler yaşanır.', EN: 'You wait in queue, delays may occur depending on server load.' },
  'membership.studio_limits': { TR: 'Stüdyo Sınırları', EN: 'Studio Limits' },
  'membership.max_3_min': { TR: 'En fazla 3 dakikalık video yükleyebilirsin.', EN: 'You can upload up to 3 minutes of video.' },
  'membership.vip_title': { TR: 'VIP Sürüm', EN: 'VIP Version' },
  'membership.high_quality': { TR: 'Yüksek Kalite', EN: 'High Quality' },
  'membership.res_1080p': { TR: '1080p yüksek çözünürlükte, net videolar.', EN: '1080p high resolution, clear videos.' },
  'membership.unlimited_export': { TR: 'Sınırsız Export', EN: 'Unlimited Export' },
  'membership.no_daily_limit': { TR: 'Günlük export limiti yok.', EN: 'No daily export limit.' },
  'membership.perm_storage': { TR: 'Kalıcı Depolama', EN: 'Permanent Storage' },
  'membership.safe_storage': { TR: 'Dosyaların sen silene kadar güvende kalır.', EN: 'Your files are safe until you delete them.' },
  'membership.ai_voice': { TR: 'AI Ses & LipSync', EN: 'AI Voice & LipSync' },
  'membership.ai_desc': { TR: 'Kendi sesin haricinde yapay zeka ile otomatik seslendirme ve dudak senkronizasyonu.', EN: 'Automatic voiceover and lip synchronization with AI besides your own voice.' },
  'membership.fast_process': { TR: 'Öncelikli İşlem', EN: 'Priority Processing' },
  'membership.no_queue': { TR: 'Kuyrukta beklemeden en hızlı şekilde render alırsın.', EN: 'You get the fastest render without waiting in queue.' },
  'membership.large_studio': { TR: 'Geniş Stüdyo', EN: 'Large Studio' },
  'membership.max_10_min': { TR: '10 dakikaya kadar video yükleyebilirsin.', EN: 'You can upload up to 10 minutes of video.' },
  'membership.demo_notice': { TR: 'Ücretsiz public demo sürümündesin.', EN: 'You are on the free public demo version.' },
  'membership.billing_notice': { TR: 'Tam sürüm ve ödeme entegrasyonu (Stripe/Iyzico) ürünleşme aşamasında aktif edilecektir.', EN: 'Full version and payment integration (Stripe/Iyzico) will be activated in the productization phase.' },

  // OdaKur
  'room.error': { TR: 'İşlem başarısız.', EN: 'Operation failed.' },
  'room.create_title': { TR: 'Yeni Oyun Odası Kur', EN: 'Create New Game Room' },
  'room.create_desc': { TR: 'Bir sahne seç ve arkadaşlarını davet et.', EN: 'Select a scene and invite your friends.' },
  'room.own_studio': { TR: 'Kendi Stüdyon', EN: 'Your Own Studio' },
  'room.submit_new': { TR: 'Yeni Sahne Gönder', EN: 'Submit New Scene' },
  'room.my_drafts': { TR: 'Taslaklarım', EN: 'My Drafts' },
  'room.community': { TR: 'DublajLab Topluluğu', EN: 'DublajLab Community' },
  'room.popular': { TR: 'Popüler Sahneler', EN: 'Popular Scenes' },
  'room.newest': { TR: 'Yeni Eklenenler', EN: 'Newest Additions' },
  'room.credit_balance': { TR: 'Kredi Bakiye:', EN: 'Credit Balance:' },
  'room.insufficient': { TR: 'Yetersiz', EN: 'Insufficient' },
  'room.start': { TR: 'Oyuna Başla', EN: 'Start Game' },
  'room.not_selected': { TR: 'Seçilmedi', EN: 'Not Selected' },
  'room.err_no_scene': { TR: 'Sahne seçmedin.', EN: 'You haven\'t selected a scene.' },
  'room.err_no_credit': { TR: 'Kredin yetersiz.', EN: 'Insufficient credits.' },

  // SecurityCheck
  'security.check': { TR: 'Güvenlik Kontrolü', EN: 'Security Check' },
  'security.safe': { TR: 'Bağlantı Güvenli', EN: 'Connection Secure' },
  'security.connecting': { TR: 'DublajLab sunucularına bağlanılıyor...', EN: 'Connecting to DublajLab servers...' },
  'security.verifying': { TR: 'Tarayıcı imzası doğrulanıyor...', EN: 'Verifying browser signature...' },
  'security.bot_check': { TR: 'Güvenlik kontrolü yapılıyor...', EN: 'Running security checks...' },
  'security.redirecting': { TR: 'Yönlendiriliyor...', EN: 'Redirecting...' },

  // ReportModal
  'report.copyright': { TR: 'Telif Hakkı İhlali', EN: 'Copyright Violation' },
  'report.inappropriate': { TR: 'Uygunsuz / Sakıncalı İçerik', EN: 'Inappropriate Content' },
  'report.misleading': { TR: 'Yanıltıcı İçerik / Deepfake', EN: 'Misleading Content / Deepfake' },
  'report.personal_data': { TR: 'Kişisel Veri İhlali', EN: 'Personal Data Violation' },
  'report.other': { TR: 'Diğer', EN: 'Other' },
  'report.success': { TR: 'Raporunuz başarıyla alındı. Teşekkür ederiz.', EN: 'Your report has been received successfully. Thank you.' },
  'report.error': { TR: 'Rapor gönderilemedi.', EN: 'Failed to send report.' },
  'report.title': { TR: 'İçeriği Raporla', EN: 'Report Content' },
  'report.desc': { TR: 'Ek Açıklama (İsteğe Bağlı)', EN: 'Additional Description (Optional)' },
  'report.placeholder': { TR: 'Detayları buraya yazabilirsiniz...', EN: 'You can write the details here...' },
  'report.cancel': { TR: 'İptal', EN: 'Cancel' },
  'report.submitting': { TR: 'Gönderiliyor...', EN: 'Submitting...' },
  'report.submit': { TR: 'Raporla', EN: 'Report' },

  // PlatformNavbar
  'nav.open_menu': { TR: 'Menüyü Aç', EN: 'Open Menu' },
  'nav.close_menu': { TR: 'Menüyü Kapat', EN: 'Close Menu' },

  // AuthPage
  'auth.default_name': { TR: 'Dublajcı', EN: 'Dubber' },

  // AdminOpsPanel
  'admin.metrics_error': { TR: 'Sistem metrikleri alınamadı.', EN: 'Failed to get system metrics.' },
  'admin.data_error': { TR: 'Veri yüklenemedi.', EN: 'Data could not be loaded.' },
  'admin.subtitle': { TR: 'Uygulama sağlığı ve temel metrikler.', EN: 'Application health and key metrics.' },
  'admin.infra': { TR: 'Altyapı', EN: 'Infrastructure' },
  'admin.db': { TR: 'Veritabanı', EN: 'Database' },
  'admin.on': { TR: 'Açık', EN: 'On' },
  'admin.off': { TR: 'Kapalı', EN: 'Off' },
  'admin.write_perm': { TR: 'Yazma İzni', EN: 'Write Permission' },
  'admin.users': { TR: 'Kullanıcılar', EN: 'Users' },
  'admin.total_users': { TR: 'Toplam Kullanıcı', EN: 'Total Users' },
  'admin.vip_users': { TR: 'Aktif VIP Kullanıcı', EN: 'Active VIP Users' },
  'admin.success_export': { TR: 'Başarılı Export', EN: 'Successful Export' },
  'admin.failed_export': { TR: 'Hatalı Export', EN: 'Failed Export' },
  'admin.public_shares': { TR: 'Açık Paylaşımlar', EN: 'Public Shares' },
  'admin.payments': { TR: 'Ödemeler (Shopier)', EN: 'Payments (Shopier)' },
  'admin.paid': { TR: 'Başarılı (Paid)', EN: 'Successful (Paid)' },
  'admin.failed_pay': { TR: 'Başarısız (Failed)', EN: 'Failed' },
  'admin.title': { TR: 'Başlık', EN: 'Title' },
  'admin.no_failed': { TR: 'Son zamanlarda hata alan proje bulunamadı.', EN: 'No projects with errors found recently.' },
  'admin.last_update': { TR: 'Son güncelleme', EN: 'Last updated' },
  'admin.refresh': { TR: 'Yenile', EN: 'Refresh' },
  'admin.user_management': { TR: 'Kullanıcı ve VIP Yönetimi', EN: 'User and VIP Management' },
  'admin.user_management_hint': { TR: 'Kullanıcı ara; doğrulanmış işlemler için 30 günlük VIP aç veya kapat.', EN: 'Search users; grant or remove 30-day VIP after verification.' },
  'admin.search_users': { TR: 'Ad veya e-posta ara', EN: 'Search name or email' },
  'admin.grant_vip': { TR: '30 gün VIP ver', EN: 'Grant VIP for 30 days' },
  'admin.remove_vip': { TR: 'VIP kaldır', EN: 'Remove VIP' },
  'admin.vip_granted': { TR: 'VIP erişimi açıldı.', EN: 'VIP access granted.' },
  'admin.vip_removed': { TR: 'VIP erişimi kaldırıldı.', EN: 'VIP access removed.' },
  'admin.membership_error': { TR: 'Üyelik güncellenemedi.', EN: 'Membership could not be updated.' },
  'admin.no_users': { TR: 'Kullanıcı bulunamadı.', EN: 'No users found.' },
  'admin.audit_logs': { TR: 'Yönetici İşlem Kayıtları', EN: 'Admin Audit Logs' },
  'admin.no_audit_logs': { TR: 'Henüz yönetici işlemi yok.', EN: 'No admin actions yet.' },
  'admin.panel_title': { TR: 'Sistem Durumu (Ops)', EN: 'System Status (Ops)' },
  'admin.total_projects': { TR: 'Toplam Proje', EN: 'Total Projects' },
  'admin.pending': { TR: 'Bekleyen', EN: 'Pending' },
  'admin.recent_failed': { TR: 'Son Hata Alan Projeler', EN: 'Recent Failed Projects' },
  'preview.badge': { TR: 'Tasarım önizlemesi · Yakında', EN: 'Design preview · Coming soon' },
  'preview.room_title': { TR: 'Çok oyunculu odalar henüz aktif değil', EN: 'Multiplayer rooms are not active yet' },
  'preview.room_desc': { TR: 'Oda kodu, oyuncu eşleştirme ve kredi sistemi için henüz güvenli bir backend akışı yok. Şimdilik tek kişilik dublaj stüdyosunu kullanabilirsin.', EN: 'Room codes, player matching, and credits do not have a production backend yet. You can use the solo dubbing studio for now.' },
  'preview.use_studio': { TR: 'Dublaj stüdyosuna dön', EN: 'Return to dubbing studio' },
  'preview.credits_title': { TR: 'Kredi sistemi henüz aktif değil', EN: 'Credits are not active yet' },
  'preview.credits_desc': { TR: 'Bu ekranda sahte bakiye veya işlem göstermiyoruz. Güncel Free/VIP özelliklerini üyelik sayfasında inceleyebilirsin.', EN: 'We do not show a fake balance or transactions here. Review the current Free/VIP features on the membership page.' },
  'preview.view_membership': { TR: 'Üyelikleri incele', EN: 'View memberships' },
  'preview.profile_title': { TR: 'Topluluk profil istatistikleri yakında', EN: 'Community profile statistics are coming soon' },
  'preview.profile_desc': { TR: 'Seviye, XP, arkadaş ve tepki sayıları henüz hesaplanmadığı için gerçek olmayan istatistikler göstermiyoruz.', EN: 'Levels, XP, friends, and reactions are not calculated yet, so we do not display invented statistics.' },
  'preview.scenes_title': { TR: 'Sahne yayınlama stüdyosu yakında', EN: 'Scene publishing studio is coming soon' },
  'preview.scenes_desc': { TR: 'İnceleme ve yayınlama iş akışı tamamlanana kadar burada sahte taslak ve yayın sayılarını göstermiyoruz.', EN: 'Until review and publishing are implemented, we do not show fake draft or publication counts here.' },
  'preview.rights_notice': { TR: 'Yalnızca haklarına sahip olduğun, kendi ürettiğin veya açık lisanslı videoları kullan.', EN: 'Only use videos you own, created yourself, or that have an open license.' },
  'preview.upload_own': { TR: 'Kendi videonu yükle', EN: 'Upload your own video' },
  'scene.load_error': { TR: 'Sahne detayları yüklenemedi.', EN: 'Scene details could not be loaded.' },
  'scene.loading': { TR: 'Yükleniyor...', EN: 'Loading...' },
  'scene.not_found': { TR: 'Sahne bulunamadı.', EN: 'Scene not found.' },
  'scene.back': { TR: 'Geri dön', EN: 'Go back' },
  'scene.breadcrumb': { TR: 'Ana sayfa / Sahneler', EN: 'Home / Scenes' },
  'scene.characters': { TR: 'Karakter', EN: 'Characters' },
  'scene.duration': { TR: 'Süre', EN: 'Duration' },
  'scene.plays': { TR: 'Oynanma', EN: 'Plays' },
  'scene.play_solo': { TR: 'Kendi sesinle dublajla', EN: 'Dub with your own voice' },
  'scene.choose_another': { TR: 'Başka sahne seç', EN: 'Choose another scene' },
  'scene.solo_hint': { TR: 'Sahnedeki tüm replikleri sırayla kendi sesinle kaydedersin.', EN: 'You record every line in the scene with your own voice.' },
  'scene.how': { TR: 'Bu sahne nasıl dublajlanır?', EN: 'How do you dub this scene?' },
  'scene.step_select': { TR: 'Sahneyi seç', EN: 'Choose scene' },
  'scene.step_select_title': { TR: 'Tek kişilik akışı başlat', EN: 'Start the solo flow' },
  'scene.step_select_desc': { TR: 'Sahneyi seç ve hazır replik zaman çizelgesini aç.', EN: 'Choose the scene and open its prepared line timeline.' },
  'scene.step_record_title': { TR: 'Replikleri kaydet', EN: 'Record the lines' },
  'scene.step_record_desc': { TR: 'Sıran geldiğinde mikrofonla kendi sesini kaydet.', EN: 'Record your voice with the microphone when each line begins.' },
  'scene.step_mix_title': { TR: 'Otomatik miks', EN: 'Automatic mix' },
  'scene.step_mix_desc': { TR: 'Sistem orijinal sesi kısar ve kayıtlarını zaman çizelgesine yerleştirir.', EN: 'The system lowers the original audio and places your recordings on the timeline.' },
  'scene.step_download_title': { TR: 'MP4 indir', EN: 'Download MP4' },
  'scene.step_download_desc': { TR: 'Altyazıları gömülmüş videonu indir.', EN: 'Download your video with burned-in subtitles.' },
  'report.question': { TR: 'Bu dublaj neden uygunsuz?', EN: 'Why is this dub inappropriate?' },
  'report.reason': { TR: 'Sebep', EN: 'Reason' },
  'report.details': { TR: 'Ek açıklama (isteğe bağlı)', EN: 'Additional details (optional)' },
  // AdminModerationPanel
  'mod.reports_error': { TR: 'Raporlar yüklenemedi.', EN: 'Failed to load reports.' },
  'mod.status_updated': { TR: 'Rapor durumu güncellendi.', EN: 'Report status updated.' },
  'mod.action_failed': { TR: 'İşlem başarısız.', EN: 'Operation failed.' },
  'mod.visible_comments': { TR: 'Görünür Yorumlar', EN: 'Visible Comments' },
  'mod.hide_comment': { TR: 'Yorumu gizle', EN: 'Hide comment' },
  'mod.comment_hide_confirm': { TR: 'Bu yorumu gizlemek istediğine emin misin?', EN: 'Are you sure you want to hide this comment?' },
  'mod.comment_hidden': { TR: 'Yorum gizlendi.', EN: 'Comment hidden.' },
  'mod.no_comments': { TR: 'Moderasyon bekleyen görünür yorum yok.', EN: 'There are no visible comments awaiting moderation.' },
  'mod.panel_title': { TR: 'Moderasyon Paneli', EN: 'Moderation Panel' },
  'mod.hide_project': { TR: 'Projeyi gizle', EN: 'Hide project' },
  'common.date': { TR: 'Tarih', EN: 'Date' },
  'common.seconds_short': { TR: 'sn', EN: 'sec' },
  'common.details': { TR: 'Detay', EN: 'Details' },
  'common.project_id': { TR: 'Proje ID', EN: 'Project ID' },
  'mod.hide_confirm': { TR: 'Bu projeyi gizlemek istediğinize emin misiniz?', EN: 'Are you sure you want to hide this project?' },
  'mod.hidden_success': { TR: 'Proje gizlendi ve rapor kapatıldı.', EN: 'Project hidden and report closed.' },
  'mod.subtitle': { TR: 'Kullanıcı bildirimlerini ve şüpheli içerikleri yönetin.', EN: 'Manage user notifications and suspicious content.' },
  'mod.pending': { TR: 'Bekleyen Raporlar', EN: 'Pending Reports' },
  'mod.resolved': { TR: 'Çözülen Raporlar', EN: 'Resolved Reports' },
  'mod.reporter': { TR: 'Rapor Eden', EN: 'Reporter' },
  'mod.reason': { TR: 'Sebep', EN: 'Reason' },
  'mod.status': { TR: 'Durum', EN: 'Status' },
  'mod.close': { TR: 'Kapat', EN: 'Close' },
  'mod.hide_punish': { TR: 'Gizle (Ceza)', EN: 'Hide (Punish)' },
  'mod.no_pending': { TR: 'Henüz bekleyen rapor yok.', EN: 'No pending reports yet.' },
  'mod.no_resolved': { TR: 'Geçmişte çözülmüş rapor yok.', EN: 'No resolved reports in the past.' },

  // Footer
  'footer.desc': { TR: 'Portföy ve teknoloji demosu.', EN: 'Portfolio and technology demo.' },
  'footer.links.product': { TR: 'Ürün', EN: 'Product' },
  'footer.links.play': { TR: 'Stüdyo', EN: 'Studio' },
  'footer.links.scenes': { TR: 'Hazır Sahneler', EN: 'Templates' },
  'footer.links.dubs': { TR: 'Topluluk', EN: 'Community' },
  'footer.links.daily': { TR: 'Günün Dublajı', EN: 'Daily Dub' },
  'footer.links.resources': { TR: 'Kaynaklar', EN: 'Resources' },
  'footer.links.howto': { TR: 'Nasıl Kullanılır?', EN: 'How to Use?' },
  'footer.links.legal': { TR: 'Yasal', EN: 'Legal' },
  'footer.links.privacy': { TR: 'Gizlilik', EN: 'Privacy' },
  'footer.links.terms': { TR: 'Kullanım Koşulları', EN: 'Terms of Use' },
  'footer.links.copyright': { TR: 'Telif Hakkı', EN: 'Copyright' },
  'footer.links.suggest': { TR: 'Sahne Öner', EN: 'Suggest Scene' },
  'footer.links.contact': { TR: 'İletişim', EN: 'Contact' },
  'footer.links.about': { TR: 'Hakkımızda', EN: 'About Us' },
  'footer.links.corporate': { TR: 'Kurumsal', EN: 'Corporate' },
  'toast.social_soon': { TR: 'DublajLab resmi sosyal medya hesabı yakında açılacak.', EN: 'DublajLab official social media account will be opened soon.' },
  'toast.suggest_soon': { TR: 'Sahne önerme özelliği yakında.', EN: 'Scene suggestion feature coming soon.' },
  'toast.contact_soon': { TR: 'İletişim paneli yakında.', EN: 'Contact panel coming soon.' },
  'social.soon': { TR: 'Resmi hesap yakında', EN: 'Official account soon' },
  // Legal Modal
  'legal.title': { TR: 'Yasal ve Kurumsal', EN: 'Legal & Corporate' },
  'legal.subtitle': { TR: 'Public Beta Bilgilendirmesi', EN: 'Public Beta Information' },
  'legal.close': { TR: 'Kapat', EN: 'Close' },
  
  'legal.about.title': { TR: 'Hakkımızda (Taslak)', EN: 'About Us (Draft)' },
  'legal.about.p1': { TR: 'DublajLab, kısa videolarınızı tarayıcı üzerinden kendi sesinizle dublajlamanızı sağlayan yaratıcı bir medya aracıdır.', EN: 'DublajLab is a creative media tool that allows you to dub your short videos with your own voice directly via the browser.' },
  'legal.about.p2': { TR: 'Bu platform şu an "Public Beta" aşamasındadır. Kullanıcıların yaratıcılıklarını sergilemeleri ve portföy içerikleri üretmeleri için tasarlanmıştır.', EN: 'This platform is currently in "Public Beta". It is designed for users to showcase their creativity and produce portfolio content.' },
  'legal.about.p3': { TR: 'Ekibimiz, video düzenleme süreçlerini olabildiğince basitleştirerek herkesin kendi sesinden hikayeler anlatabilmesini hedefliyor.', EN: 'Our team aims to simplify video editing processes as much as possible so that everyone can tell stories with their own voice.' },

  'legal.contact.title': { TR: 'İletişim (Taslak)', EN: 'Contact (Draft)' },
  'legal.contact.p1': { TR: 'DublajLab Public Beta süresince resmi destek kanallarımız sınırlıdır. Geri bildirimleriniz ve hata bildirimleriniz bizim için çok değerlidir.', EN: 'During the DublajLab Public Beta, our official support channels are limited. Your feedback and bug reports are very valuable to us.' },
  'legal.contact.p2': { TR: 'Bize aşağıdaki e-posta adresinden ulaşabilirsiniz:', EN: 'You can reach us at the following e-mail address:' },
  'legal.contact.p3': { TR: '* Sosyal medya hesaplarımız yakında aktif edilecektir.', EN: '* Our social media accounts will be activated soon.' },

  'legal.privacy.title': { TR: 'Gizlilik Politikası (Taslak)', EN: 'Privacy Policy (Draft)' },
  'legal.privacy.p1': { TR: 'DublajLab, kişisel verilerinizin güvenliğine önem verir. Bu metin Public Beta süreci için bir bilgilendirmedir.', EN: 'DublajLab cares about the security of your personal data. This text is an information for the Public Beta process.' },
  'legal.privacy.li1': { TR: 'Medya Verileri: Tarayıcı üzerinden kaydettiğiniz sesler sadece export işlemi için sunucuya iletilir ve işlem bittikten sonra geçici sunuculardan silinir.', EN: 'Media Data: The sounds you record via the browser are only transmitted to the server for export and are deleted from temporary servers after the process is finished.' },
  'legal.privacy.li2': { TR: 'Kalıcı Saklama: Üye olan kullanıcıların projeleri ve indirmeye hazır MP4 çıktıları sunucularımızda saklanır. Depolama temizlik politikalarımız (cleanup) eski dosyaları silebilir.', EN: 'Persistent Storage: The projects and ready-to-download MP4 outputs of registered users are stored on our servers. Our storage cleanup policies can delete old files.' },
  'legal.privacy.li3': { TR: 'Üçüncü Taraflar: Verileriniz izniniz olmadan üçüncü taraf reklam şirketlerine satılmaz. Sadece hizmeti sunmak için gereken bulut sağlayıcıları (örn. Cloudflare, Railway) kullanılır.', EN: 'Third Parties: Your data is not sold to third-party advertising companies without your permission. Only cloud providers (e.g. Cloudflare, Railway) required to provide the service are used.' },

  'legal.terms.title': { TR: 'Kullanım Koşulları (Taslak)', EN: 'Terms of Use (Draft)' },
  'legal.terms.p1': { TR: 'DublajLab hizmetlerini kullanarak aşağıdaki koşulları kabul etmiş sayılırsınız:', EN: 'By using DublajLab services, you are deemed to have accepted the following conditions:' },
  'legal.terms.li1': { TR: 'Kullanıcılar sisteme yükledikleri tüm video ve ses içeriklerinden bizzat sorumludur.', EN: 'Users are personally responsible for all video and audio content they upload to the system.' },
  'legal.terms.li2': { TR: 'Hizmet şu an "Public Beta" aşamasında olup, kesintiler veya veri kayıpları yaşanabilir.', EN: 'The service is currently in "Public Beta" and interruptions or data loss may occur.' },
  'legal.terms.li3': { TR: 'Kötüye kullanım (DDoS, API limitlerini aşma çabası) durumunda hesabınız veya IP adresiniz engellenebilir.', EN: 'In case of abuse (DDoS, effort to exceed API limits), your account or IP address may be blocked.' },

  'legal.copyright.title': { TR: 'Telif Bildirimi (Taslak)', EN: 'Copyright Notice (Draft)' },
  'legal.copyright.p1': { TR: 'DublajLab platformunda paylaşılan veya yüklenen içeriklerin fikri mülkiyet haklarına saygı duyuyoruz.', EN: 'We respect the intellectual property rights of the content shared or uploaded on the DublajLab platform.' },
  'legal.copyright.li1': { TR: 'Sadece kullanım hakkına sahip olduğunuz veya kamuya açık (CC0 vb.) videoları yükleyin.', EN: 'Only upload videos that you have the right to use or are public (CC0 etc.).' },
  'legal.copyright.li2': { TR: 'Gerçek kişilerin seslerini taklit etmek (deepfake) veya onları yanıltıcı durumlara sokmak yasaktır.', EN: 'Imitating the voices of real people (deepfake) or putting them in misleading situations is prohibited.' },
  'legal.copyright.li3': { TR: 'Eğer telif hakkına sahip olduğunuz bir materyalin izinsiz kullanıldığını düşünüyorsanız, iletişim kanallarımızdan bize bildirebilirsiniz. İçerik incelenip yayından kaldırılacaktır.', EN: 'If you think that a material you own the copyright is used without permission, you can report it to us via our communication channels. The content will be reviewed and removed.' },

  'legal.refund.title': { TR: 'İade ve İptal Koşulları (Taslak)', EN: 'Refund and Cancellation Policy (Draft)' },
  'legal.refund.p1': { TR: 'Not: Şu an sistemimizde Shopier ödeme entegrasyonu (VIP) aktif değildir. Aşağıdaki kurallar ödeme alındığında geçerli olacaktır.', EN: 'Note: Currently, Shopier payment integration (VIP) is not active in our system. The following rules will be valid when payment is received.' },
  'legal.refund.li1': { TR: 'Satın alınan VIP üyelikler dijital hizmet niteliğinde olduğundan, hizmet kullanılmaya başlandıktan sonra cayma hakkı kural olarak geçerli değildir.', EN: 'Since purchased VIP memberships are in the nature of digital services, the right of withdrawal is generally not valid after the service has started to be used.' },
  'legal.refund.li2': { TR: 'Teknik bir nedenden ötürü (sistemin sürekli çökmesi vb.) vaat edilen hizmet hiç verilememişse, destek talebi üzerinden iade incelenebilir.', EN: 'If the promised service cannot be provided at all due to a technical reason (constant system crash, etc.), a refund can be reviewed via a support request.' },

  'legal.distance.title': { TR: 'Mesafeli Satış Sözleşmesi (Taslak)', EN: 'Distance Selling Contract (Draft)' },
  'legal.distance.p1': { TR: 'Madde 1 - Taraflar: Bu sözleşme DublajLab (Satıcı) ile VIP/Premium hizmet alan kullanıcı (Alıcı) arasındadır. (Şu an test aşamasındadır, yasal satıcı ünvanı atanmamıştır).', EN: 'Article 1 - Parties: This contract is between DublajLab (Seller) and the user receiving VIP/Premium service (Buyer). (Currently in testing phase, legal seller title not assigned).' },
  'legal.distance.p2': { TR: 'Madde 2 - Konu: Sözleşmenin konusu, alıcının dijital VIP hizmeti satın alması ve bu hizmetin elektronik ortamda anında teslimidir.', EN: 'Article 2 - Subject: The subject of the contract is the buyer purchasing digital VIP service and immediate delivery of this service electronically.' },
  'legal.distance.p3': { TR: 'Madde 3 - Teslimat: Satın alım tamamlandıktan hemen sonra üyelik statüsü güncellenir ve yüksek çözünürlük gibi özellikler aktifleşir.', EN: 'Article 3 - Delivery: Immediately after the purchase is completed, the membership status is updated and features such as high resolution are activated.' },
  'legal.distance.p4': { TR: 'Not: Gerçek ticari faaliyet başladığında bu sayfa hukuk metni ile güncellenecektir.', EN: 'Note: When real commercial activity starts, this page will be updated with a legal text.' },

  'footer.links.refund': { TR: 'İade ve İptal', EN: 'Refund Policy' },
  'footer.links.distance': { TR: 'Mesafeli Satış', EN: 'Distance Selling' },
  'footer.links.oda_kur': { TR: 'Oda kur', EN: 'Create Room' },
  'footer.disclaimer': { TR: 'DublajLab kullanıcıların gönderdiği içeriklerde gerekli kullanım haklarına sahip olduklarını beyan etmelerini zorunlu tutar. Hak sahibinden geçerli bir ihlal bildirimi alınırsa içerik incelenir ve gerekirse erişimden kaldırılır.', EN: 'DublajLab requires users to declare that they have the necessary usage rights in the content they submit. If a valid infringement notice is received from the right holder, the content is reviewed and removed if necessary.' },


  // Auto-added keys
  'account.del_title': { TR: 'Hesabı kalıcı olarak sil', EN: 'Delete account permanently' },
  'account.del_warning': { TR: 'Bu işlem geri alınamaz. Devam etmeden önce aşağıdakileri oku:', EN: 'This action cannot be undone. Read the following before continuing:' },
  'account.del_kvkk': { TR: 'Verilerinin nasıl işlendiğini KVKK aydınlatma metninde okuyabilirsin.', EN: 'You can read about how your data is processed in the privacy policy.' },
  'account.del_intent': { TR: 'Hesabımı silmek istiyorum', EN: 'I want to delete my account' },
  'admin.reject_report': { TR: 'Raporu Reddet (Görmezden Gel)', EN: 'Reject Report (Ignore)' },
  'admin.no_reports': { TR: 'Bekleyen veya geçmiş rapor bulunamadı.', EN: 'No pending or past reports found.' },
  'admin.data_load_failed': { TR: 'Veri yüklenemedi.', EN: 'Failed to load data.' },
  'admin.no_recent_errors': { TR: 'Son zamanlarda hata alan proje bulunamadı.', EN: 'No recently failed projects found.' },
  'membership.studio_vip': { TR: 'Stüdyo VIP', EN: 'Studio VIP' },
  'scene.step_studio': { TR: 'Stüdyo', EN: 'Studio' },
  'scene.step_processing': { TR: 'İşleme', EN: 'Processing' },
  'scene.step_result': { TR: 'Sonuç', EN: 'Result' },
  'library.file_expired_desc': { TR: 'Dosya sunucudan silinmiş (Süre aşımı)', EN: 'File deleted from server (Expired)' },
  'library.status_expired': { TR: 'Süresi Dolmuş', EN: 'Expired' },

  // Fixed & injected keys
  'account.public_profile': { TR: 'Herkese açık profilim', EN: 'My public profile' },
  'account.cancel': { TR: 'Vazgeç', EN: 'Cancel' },
  'admin.action': { TR: 'İşlem', EN: 'Action' },
  'library.status_completed': { TR: 'Tamamlandı', EN: 'Completed' },
  'library.status_processing': { TR: 'İşleniyor', EN: 'Processing' },
  'library.status_failed': { TR: 'Başarısız', EN: 'Failed' },
  'library.download': { TR: 'İndir', EN: 'Download' },
  'nav.library': { TR: 'Kataloğum', EN: 'My Library' },
  'template.ofis-surprizi.title': { TR: 'Ofiste Beklenmedik An', EN: 'Unexpected Office Moment' },
  'template.ofis-surprizi.desc': { TR: 'Kısa ve tempolu bir ofis sahnesi için üç repliklik örnek zaman çizelgesi.', EN: 'A three-line sample timeline for a short, fast-paced office scene.' },
  'template.uzay-gorevi.title': { TR: 'Mini Uzay Görevi', EN: 'Mini Space Mission' },
  'template.uzay-gorevi.desc': { TR: 'İki karakterlik kısa bir uzay macerası için örnek replikler.', EN: 'Sample lines for a short, two-character space adventure.' },
  'template.comedy-reaction.title': { TR: 'Komik Tepki', EN: 'Funny Reaction' },
  'template.comedy-reaction.desc': { TR: 'Şaşırtıcı bir ana verilen hızlı tepkileri seslendirmek için kısa bir sahne taslağı.', EN: 'A short scene draft to dub quick reactions to a surprising moment.' },
  'template.dramatic-line.title': { TR: 'Dramatik Karar', EN: 'Dramatic Decision' },
  'template.dramatic-line.desc': { TR: 'Duygulu tonlama ve kısa duraklamalarla çalışmak için iki repliklik sahne taslağı.', EN: 'A two-line scene draft for working on emotional intonation and short pauses.' },
  'template.product-demo.title': { TR: 'Ürün Tanıtımı', EN: 'Product Pitch' },
  'template.product-demo.desc': { TR: 'Kendi ürününüzü veya portföy projenizi anlatabileceğiniz nötr bir demo akışı.', EN: 'A neutral demo flow where you can pitch your own product or portfolio project.' },
  'category.Komedi': { TR: 'Komedi', EN: 'Comedy' },
  'category.Bilim Kurgu': { TR: 'Bilim Kurgu', EN: 'Sci-Fi' },
  'category.Dram': { TR: 'Dram', EN: 'Drama' },
  'category.Tanıtım': { TR: 'Tanıtım', EN: 'Promo' },

  // Showcase mock keys
  'dubs.demo_dub_title': { TR: 'Demo Dublaj #{i}', EN: 'Demo Dub #{i}' },
  'dubs.player_prefix': { TR: 'Oyuncu', EN: 'Player' },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function translate(key: string, language: Language): string {
  return translations[key]?.[language] || key;
}

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const storedLanguage = typeof window === 'undefined'
      ? null
      : window.localStorage.getItem('dublajlab-language');
    return storedLanguage === 'EN' ? 'EN' : 'TR';
  });

  useEffect(() => {
    window.localStorage.setItem('dublajlab-language', language);
    document.documentElement.lang = language === 'TR' ? 'tr' : 'en';
  }, [language]);

  const t = (key: string): string => {
    return translate(key, language);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
